### ISSUE TITLE
Please support Shift+Insert for paste

### ISSUE THREAD

**Issue by nigels-com** [sedwards2009/extraterm#10]
`Ctrl-Shift-V` does work, but I find `Shift+Insert` a bit less contorting.

**Comment by philer** [comment]
I guess "please support fully configurable keyboard short cuts" would be a more sustainable goal. :D

**Comment by nigels-com** [comment]
Low hanging fruit.

**Comment by sedwards2009** [comment]
keyboard configuration is definitely part of the plan.

**Comment by nigels-com** [comment]
Awesome, thanks!
