### ISSUE TITLE
Clear Scrollback on Ubuntu 18

### ISSUE THREAD

**Issue by 1e1f** [sedwards2009/extraterm#101]
Not sure if this is limited to Ubuntu 18 or not, but the "clear scrollback" command doesn't seem to do anything, nor does limiting the scrollback buffer size. Hopefully I've understood this feature correctly. Ideally "clear scrollback" would also have a shortcut like ctrl+shift+k (which is what I understand to be the shortcut for clear scrollback in the app Hyper).

**Comment by sedwards2009** [comment]
(Sorry about the slow response.)

You are right. It appears to be broken at the moment. Thanks for reporting.

**Comment by sedwards2009** [comment]
Fixed in 0.36.2.

**Comment by WillPlatnick** [comment]
This is happening to me in 0.38.1.
