### ISSUE TITLE
Allow command-line options for a session type

### ISSUE THREAD

**Issue by NiklasRosenstein** [sedwards2009/extraterm#102]
I would like to pass the `--login` option to the Git for Windows bash, but currently you can only specify an executable and no additional arguments.

![image](https://user-images.githubusercontent.com/1318438/41778910-6df4be62-7630-11e8-87f3-ed59bea7c21a.png)

**Comment by sedwards2009** [comment]
thanks for reporting this.

**Comment by NiklasRosenstein** [comment]
If you can give me a point to start from in the extraterm source, I would be happy to try and contribute this feature.

**Comment by sedwards2009** [comment]
I didn't see your reply until just today.

Adding a text field for arguments to the shell should be pretty straight forward. All of the session related code is done via extensions and lives under the `extensions` directory. The different session types have a back-end which does the real work (unix pty, proxy/cygwin/WSL or winpty on Windows) and a front-end which is just the editor bit you see in the Settings tab. Following and copying how the 'executable' field works is the best approach.

**Comment by sedwards2009** [comment]
@nshanny Yes, please do. A PR based on `master` would be great.

**Comment by sedwards2009** [comment]
PR #121

**Comment by sedwards2009** [comment]
Released in 0.37.0.
