### ISSUE TITLE
Does not support Chinese

### ISSUE THREAD

**Issue by johncyuan** [sedwards2009/extraterm#105]
Overlapping when mangaro system can not input Chinese and display Chinese

**Comment by sedwards2009** [comment]
The real problem here is that I don't know enough about how Chinese is meant to work in a terminal to actually go fix the Chinese support in Extraterm. I also don't know much about how Chinese input works either. Someone with the right knowledge needs to help first otherwise there is little I can do.

**Comment by nemonein** [comment]
Thank you for your great software.
Unfortunately, this is the same for Korean. Korean, Chinese and Japanese have similar input system. When you find the problem, that would fix it for these languages.

I'm using KDE Neon(Kubuntu based Distro.), but typing Korean is somewhat weird.
Other Electron based application, for example, Atom, has no problem like this, so I hope you could find a solution.

**Comment by sedwards2009** [comment]
@nemonein I've done some testing with Japanese on Windows 10 and macOS, but I haven't been able to figure out how to get IME working on a Kubuntu (which I use). Can you explain or point me to a guide which can tell me how to set this up? All the stuff I could find looked very out of date.

**Comment by nemonein** [comment]
@sedwards2009 Thank you for your response. I don't know exactly what you want, and I have no idea about Japanese input system. However, I guess using Japanese with fcitx would be the same as Korean.

Here's how to do on Kubuntu.
```
sudo apt install fcitx fcitx-mozc
im-config -n fcitx
```
fcitx is input system, and fcitx-mozc is a Japanese engine for fcitx. You could get the info [here](https://wiki.archlinux.org/index.php/fcitx).

If you don't have im-config on your system, then install it by `sudo apt install im-config`.
Reboot, and you could see the fcitx(keyboard) indicator on the system tray.

You can change the language by clicking the indicator from English(or your default language) to Japanese(or vice versa), or just use `Ctrl-Space`.

Later, you can remove all of them by,
```
im-config -n none
sudo apt remove fcitx fcitx-mozc
sudo apt autoremove
```

I hope this could help you.

**Comment by sedwards2009** [comment]
@nemonein Thanks. I've been able to get it installed, and after a bit of playing around I've got mozc set up and I can activate it for testing.

I assume it works the same as the other languages.

**Comment by sedwards2009** [comment]
I had a look at this issue last night on Linux. The biggest problem I see is the position and size of the textarea holding the temporary characters when you are busy composing with the menu system. It was misaligned and simply not big enough to show its contents before you accept the characters.

To fix this properly I need to go into my fork of Ace editor and fix a bunch of layout and positioning problems. I have to do this anyway to fix a number of other bugs I see. It might be a while before I get time to fix this issue. There are a number of "low hanging fruit" features that I want to get into Extraterm first.

**Comment by nemonein** [comment]
I'm glad you've found what causes this.
However, there's similar issues in [Simplenote](https://github.com/Automattic/simplenote-electron/issues/745).
I think extraterm and Simplenote use the same engine(electron, Ace engine), so you might find something useful there.

Good luck!

**Comment by johncyuan** [comment]
Now Chinese has been displayed normally, thank you

**Comment by sedwards2009** [comment]
@johncyuan  Cool. Let me know if there is something else blocking Chinese language output or input.
