### ISSUE TITLE
Extraterm window does not maximize over SSH

### ISSUE THREAD

**Issue by krishnakumarg1984** [sedwards2009/extraterm#106]
I am connected over SSH (with X11 forwarding) to a linux machine which has extraterm installed.  When I fire up extraterm, the window opens, but the maximize button does not work.

**Comment by sedwards2009** [comment]
I still need to test this one directly but I strongly suspect that I won't be able to fix the problem as it needs to be handled in the underlying platform (i.e. Electron).

Using a terminal emulator via X11 over SSH is a bit odd and very few people are going to hit it. This is a low prio problem.

thanks for submitting the issue though.

**Comment by krishnakumarg1984** [comment]
@sedwards2009  Let me explain why this is not a corner case and is actually quite important.

I am not convinced that the problem is with electron framework, as this issue does not occur in Terminus, another electron based terminal application with similar goals.

At my university, I have a Linux workstation in my desk. But my research group works out of another campus, where library machines provide wired access to the university's network. Now, for obvious security reasons, no user is given administrative access. Furthermore, the machines all run Windows 7 enterprise edition providing IT services with a common platform for facilitating maintanence. For obvious security reasons, no one is given administrative access. So, connecting to my Linux workstation over SSH with X11 involves using a tool which doesn't require admin rights. The only portable software which bundles SFTP, terminal and X server in a convenient package is mobaxterm which comes as a single portable zip file that is always available in any university machine on my networked home drive. Now, mobaxterm's terminal emulator is based on putty, with support only upto 256 colours and not true colour. I would like to use the cool features of extraterm. So, I log in to my own workstation over mobaxterm's ssh. And simply fire up extraterm which is installed on my workstation. Now, the resulting window cannot be maximised. I don't think it is electron issue. Many others who need portable access to their favourite terminal emulator will be in the same boat as mine. Corporate environments restricts admin rights, so one can simply use a crappy terminal emulator to SSH into own machine and simply invoke the familiar and favourite extraterm

**Comment by sedwards2009** [comment]
@krishnakumarg1984 I can't reproduce the problem here using v0.36. Can you retest this again yourself?

**Comment by sedwards2009** [comment]
@krishnakumarg1984 You can also grab the linux version from here on github, unzip it and run it directly from there. It doesn't need any kind of fancy installation process.

**Comment by krishnakumarg1984** [comment]
@sedwards2009  Nope. The problem still persists. 

I just tried this on the latest release 0.36.1 . Unable to maximise extraterm over SSH.

**Comment by hensz** [comment]
Hi!
I also have the same issue, and I'm also using MobaXTerm on Windows to connect to my Linux box. But as stated in #123 I also cannot perform any resize operation, and I also cannot move the window.

The issue occurs on v0.36.2.

**Comment by sedwards2009** [comment]
I just had a look at this and it appears the mobaxterm doesn't like the non-native title bar. Running Extraterm using a plain native title bar works fine. (You can select this in the settings tab.)

I'm not sure there is much I can do about this except add a command line option to force a native titlebar and to put the problem in the FAQ.

**Comment by krishnakumarg1984** [comment]
This information is not in the FAQ. Has the setting been forced by default on Windows?

**Comment by sedwards2009** [comment]
@krishnakumarg1984 No default setting has been changed for Windows because Extraterm on Windows works fine with the title bar.

The situation here is where Extraterm is running on _Linux_ but its interface is _displayed_ on a Windows machine via mobaxterm.
