### ISSUE TITLE
Black-Screen: a similar terminal project that is based on Electron and TypeScript

### ISSUE THREAD

**Issue by FunkMonkey** [sedwards2009/extraterm#11]
There is a very similar project called [Black Screen](https://github.com/shockone/black-screen), which also provides a terminal based on Electron and Typescript.

I just wanted to cross-link both projects. Guess they can inspire each other.

[edit] ...or even work out a compatible API and share code

**Comment by sedwards2009** [comment]
Thanks. I've been keeping an eye on Black-screen since the brutal unWelcoming Party it had on Reddit.

I'll just drop here a comment I put on reddit about how I see Black Screen and the two relate. It is all my Humble Opinion and can change at any time.

> Black Screen is a shell and terminal in one which is a somewhat more radical approach. The problem being that it is going to have trouble keeping backwards compatibility (Black screen won't easily work over ssh), and for a lot of people it is too big a jump to go from their old set up terminal+shell to a whole new shell.
> 
> Don't get me wrong. I love their vision, and the projects have an awful lot in common. Extraterm is starting with backwards compatibility in place and solid first, and then working further from there.
> 
> It would be nice if Extraterm had the display/rendering/UI capabilities that the Black Screen team needs to render their UI. Then Black Screen could be implemented as a more typical shell talking to the terminal with possibly a network in between.
