### ISSUE TITLE
Cursor sometimes dissappears

### ISSUE THREAD

**Issue by nbelakovski** [sedwards2009/extraterm#110]
Unfortunately I don't have reproduction steps for this, but sometimes the cursor on the command prompt disappears. I try to get around it for a bit by using backspace to figure out where I am, but usually I just have to open a new tab.

I'll add repro steps if I can figure it out.

**Comment by sedwards2009** [comment]
Is it possible that you went into Cursor Mode and didn't notice it?

**Comment by nbelakovski** [comment]
No, I can't move around the rest of the terminal, and I can type. It usually happens after running some command. Now that I think about it, some of those commands do some fancy stuff with things like a spinning progress bar, so may that's messing it up. I'll take a look and see if I can make a simplified example.

If it helps, I'm running on Win10 and using WSL.

**Comment by nbelakovski** [comment]
I wasn't able to reproduce it exactly, but I messed around with python's click module (which is what we're using to make the progress bar), and running the simple script I made on a terminal where the cursor had disappeared brought it back! So, at least I have a workaround now. Here's the script, although it could probably be shorter. Next time this happens, I'll mess with the script and see if I can make it shorter:
```
import click
from time import sleep
mylist = [1, 2, 3]
with click.progressbar(mylist, label="asdf") as bar:
    for i, elem in enumerate(mylist):
        sleep(1)
        elem += 1
        bar.update(i + 1)
```

**Comment by sedwards2009** [comment]
I think what is happening is that your python script is turning off the display of the cursor to do the funky progress bar, and when that script finishes (or crashes, or may be it is killed) then sometimes the terminal's cursor isn't being turned back on again. What you can do is two things: Fix up your Python script to reset and restore the terminal settings on exit. And secondly, if your terminal does get messed up then you can run the "Reset VT" command from Extraterm's command palette.

**Comment by sedwards2009** [comment]
This issue has had any activity for a long time. Closing it. If this is still a problem, then please reopen.
