### ISSUE TITLE
support terminology protocols

### ISSUE THREAD

**Issue by unmellow** [sedwards2009/extraterm#117]
[terminology](https://www.enlightenment.org/about-terminology.md) and your app are very similar so it might be a good idea to try to collab with then and or just support some of there protocols like tycat

**Comment by unmellow** [comment]
also, it would be cool to add [terminology](https://www.enlightenment.org/about-terminology)

**Comment by unmellow** [comment]
now that i think about you support playing just about every image format so i could just write an extraterm shell (if i wasn't lazy)

**Comment by sedwards2009** [comment]
I'm probably not going to support terminology's protocols directly. But I do intend to help out and implement protocols and extensions defined at the Terminal Working Group at Free Desktop: https://gitlab.freedesktop.org/terminal-wg
