### ISSUE TITLE
Zoom option when viewing images

### ISSUE THREAD

**Issue by unmellow** [sedwards2009/extraterm#118]
i can't chose what size my photo get's displayed at which is a problem if you have a low resolution SVG

**Comment by sedwards2009** [comment]
Yes, the image viewer needs a bunch of options like zoom to make it usable.

**Comment by sedwards2009** [comment]
Image viewing is coming in the next release and will include zoom. :tada:

**Comment by sedwards2009** [comment]
This was released in 0.66.0.
