### ISSUE TITLE
Default shell is always bash on OSX

### ISSUE THREAD

**Issue by Gagege** [sedwards2009/extraterm#12]
I just installed extraterm-0.5.0-darwin-x64 on OSX and then installed fish with `brew install fish`. Then I added /usr/local/bin/fish to /etc/shells and ran `chsh -s /usr/local/bin/fish` and entered my password. My default shell is now fish in the Apple Terminal and in iTerm, but when extraterm starts, it's bash.

I have logged out and logged back in. I have deleted extraterm and reinstalled it. Still, every terminal uses fish, except extraterm which is still using bash. I can start fish in extraterm by running `fish`, but I obviously want it to be the default.

Do I need to to something else in extraterm to change my default shell?

Thanks in advance.

**Comment by sedwards2009** [comment]
From a little bit of googling I see that Mac OS X doesn't store the user's shell in /etc/passwd (which is what Extraterm is reading). It uses Open Directory.

https://superuser.com/questions/191330/users-in-etc-passwd-on-mac-os-x

**Comment by Gagege** [comment]
Thanks a lot! Can't wait for the next release. Wish I had time to build it myself.

**Comment by yrizk** [comment]
checking /etc/passwd won't work for networked linux machines either. you'll need to look through the administrative database using `getent passwd`

**Comment by yrizk** [comment]
if anyone is looking for a patch for this issue, manually get your user entry from wherever it is stored. userid and groupid are the tricky parts, but you'll need the whole line seperated by colons. make sure the end of that line is the shell you want to use. Then add it to /etc/passwd with root priv. 
`sudo nano /etc/passwd`

**Comment by sedwards2009** [comment]
@yrizk Do you by any chance know of a general Linux command or call which fetches a user's shell regardless of how it is set up in the "back end"?

**Comment by yrizk** [comment]
Nope I don't know of such a thing . I would set up an or on both getent and passwd
