### ISSUE TITLE
Tries to open in second display even if that display is not connected

### ISSUE THREAD

**Issue by eSaner** [sedwards2009/extraterm#120]
I use multiple displays/monitors connected to a laptop. If I use Extraterm in a second monitor, then exit Extraterm, disconnect the second monitor and try to open Extraterm using the laptop's monitor, it opens off screen as if the second monitor is still there.

**Comment by sedwards2009** [comment]
Which operating system are we talking about?

**Comment by eSaner** [comment]
Windows 10

**Comment by Redirts** [comment]
Yep, same here. Annoying.

**Comment by sedwards2009** [comment]
There are a whole bunch of multiple monitor and DPI issues still in Electron itself. https://github.com/electron/electron/issues/10862

**Comment by sedwards2009** [comment]
Fixed in 0.14.1.
