### ISSUE TITLE
Git Bash Session Support

### ISSUE THREAD

**Issue by Dalez** [sedwards2009/extraterm#129]
I use Git Bash for development (Docker etc.) and WSL for deployment (both on Windows). Would it be possible to support Git Bash?

As far as I can see, Session Types doesn't allow me to specify a path to Git Bash (C:\Program Files\Git\git-bash.exe).

Thanks :)

**Comment by aellerton** [comment]
How to add a Git Bash terminal:
* go to settings > Session Types
* select "New Windows Console Session Type"
* set name as "Git Bash" (or whatever you like)
* set executable as `C:\Program Files\Git\bin\bash.exe` (you may need to adjust this for your system)

That works for me.

**Comment by sedwards2009** [comment]
@aellerton  thanks
