### ISSUE TITLE
Extremely slow in fedora

### ISSUE THREAD

**Issue by caedmon-kitty** [sedwards2009/extraterm#134]

**Comment by caedmon-kitty** [comment]
Extremely slow in fedora 28.  Each character takes several seconds to echo.  Happens with both txsh and zsh shells.

**Comment by sedwards2009** [comment]
Extraterm is currently using version 2.x of Electron. There have been some problems in that version regarding GPUs being blacklisted and severe performance problems for some operating systems and configurations. (for example https://github.com/electron/electron/issues/12042 )

I'll be upgrading Electron in the near future. Once that is done it will be a good idea to try Extraterm out again and let me know the problem persists.

**Comment by caedmon-kitty** [comment]
Thank you.  I'll keep an eye out for the version with the new Electron.

I used 0.29 for a long time without problems.  Then decided it might be time to update and installed 0.37.  The problem began with 0.37 for me.

Thank you,

michael

**Comment by sedwards2009** [comment]
@caedmon-kitty Is this still a problem?

**Comment by sedwards2009** [comment]
I haven't had a response from the reporter of this issue. -> Closing.

If this problem is still occurring then this issue can be reopened.
