### ISSUE TITLE
advice on how to colorize output

### ISSUE THREAD

**Issue by aellerton** [sedwards2009/extraterm#135]
Hi @sedwards2009!

Thanks for extraterm - it's awesome.

I'd like to modify extraterm so that cmd windows (which I unfortunately have to use) can have their prompt colorized? For example, I could add a setting for regex, like `^[A-Z]:\\.*>` and that would be the prompt, which might show in purple.

In a proper (i.e. Unix-like) shell, the prompt itself contains all the color codes, but we don't have that luxury with cmd.

I'm compiling using visual studio, and want to colorize that output too, but that can probably be done with a python script that outputs the usual color codes ... but would that work in a cmd window?

Thanks

**Comment by sedwards2009** [comment]
You can't really modify Extraterm to give you a custom prompt. It doesn't know where the prompt is on the screen for CMD and PowerShell. For PowerShell at least, you can set the prompt and use colours:
 https://stackoverflow.com/questions/1338453/custom-powershell-prompts CMD appears to limit you to just text though. See https://www.wikihow.com/Create-a-Custom-Windows-Command-Prompt

good luck

**Comment by aellerton** [comment]
Thanks @sedwards2009 

I found a simple solution in Windows 10. The following steps create a session type that 1) sets up Visual Studio 2017 for x86 development, 2) sets the prompt to light blue, and 3) changes to a specific directory:

* create a new batch file with content:

```
@call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars32.bat"
prompt $E[1;34m $p$g $E[0;37m
cd C:\wherever\you\want
```

* create a new "Windows Console" session
* name the session how you like
* leave the executable as `cmd.exe`
* set the arguments to: `/k C:\wherever\your-batch-file.bat` (obviously changing the filename appropriately)

**Comment by sedwards2009** [comment]
ah yes. Microsoft have been adding some support for some VT escape codes to the default console.

The situation should improve immensely in the future. MS is rolling out the new version of Windows 10 and it has a thing called ConPTY which basically adds unix style console and terminal support.
