### ISSUE TITLE
Preferences that are set for extraterm are not persistent

### ISSUE THREAD

**Issue by krishnakumarg1984** [sedwards2009/extraterm#138]
I am running both `cygwin` and `extraterm` from a network drive labelled the `home drive (H:)` by our ICT. This way I get reproducible access to a set of command line and packages on every machine in the campus (all computers run Windows 10).

I make a lot of adjustments to the appearance setting such as the colorscheme, font size etc., and then when I log in the next day (irrespective of whether from the same machine or another one), the settings all seem to revert to the defaults. Clearly, it is painful to reconfigure the settings again, only to discover that they are once again ephemeral.

How can I make the configurations persistent?

**Comment by sedwards2009** [comment]
If you change some settings, exit Extraterm, and then immediately run it again, do you have the correct settings? On Windows Extraterm will place its config file in `c:/Users/<username>/AppData/Roaming/extraterm/extraterm.json`. It sounds like your ICT set up is just wiping that directory all the time.

What I could do is add a command line option to Extraterm to specify where to place this temp directory and also the config file. And/or I could add a small config file to the Extraterm installation files to do the same thing. Then you could configure that file and make a true "portable" version of Extraterm for yourself and your campus environment.

**Comment by krishnakumarg1984** [comment]
@sedwards2009 your explanation makes sense to me. Yes,  the campus computers are set to wipe the entire C-drive and restore a university-preconfigured image. All public computers on the campus (library, training rooms, etc.) automatically reboot at 12:15 AM each night.  Only the H: drive is persistent for all students and staff to store their files.

While you make this enhancement for a truly portable setup, is there a tempporary workaround for placing the config file?

**Comment by krishnakumarg1984** [comment]
>If you change some settings, exit Extraterm, and then immediately run it again, do you have the correct settings?

yes. Till the computers reboot overnight and get restored with a custom win10 image of the university for the next day.

**Comment by sedwards2009** [comment]
The closest thing to a work around is probably manually managing and copying that directory in `AppData/Roaming`. :-/

**Comment by sedwards2009** [comment]
Just released in 0.40. See section "Changing where the configuration settings are stored" in the guide.
