### ISSUE TITLE
gnuplot

### ISSUE THREAD

**Issue by texrg** [sedwards2009/extraterm#141]
Is possible to add a gnuplot output direct to terminal?

**Comment by sedwards2009** [comment]
First you should maybe set up the shell integration or at least make sure you can run the `show` command. See http://extraterm.org/guide.html#shell-integration

Once you have `show` you can use it to show an image file in the terminal or pipe an image file into it. I haven't used gnuplot myself, but you could write a small script to run it and then immediately run `show` to display the image.

**Comment by xor256** [comment]
no show image but show .plot source code

**Comment by sedwards2009** [comment]
`show` will not convert `.plot` to an image. You have to use gnuplot first to make and image and then you can use `show` to show it.

**Comment by nigels-com** [comment]
If gnuplot is installed, I guess this wrapper would work?
https://www.npmjs.com/package/gnuplot

**Comment by sedwards2009** [comment]
@nigels-com With regards to displaying different file formats inside Extraterm, the idea is to have different viewers. There already are a number of them but they need more work, also the module/extension system needs to be more developed before it is easy to support something like gnuplot files directly.

This issue does demonstrate the usefulness of having lighter weight "filters" which can convert a file to a more common file format (e.g. a PNG image) for display by the built in a image viewer.
