### ISSUE TITLE
After sourcing the Extraterm commands, `clear` does nothing

### ISSUE THREAD

**Issue by vlad-s** [sedwards2009/extraterm#15]
As the title says, after sourcing the Extraterm commands, `clear` (Ctrl+L as well) does nothing, but clears until the last shown frame, which, in most cases, is after the last command. Using frames is extra useful, but clearing up is too, as I don't enjoy clutter on my screen.

**Comment by nigels-com** [comment]
Confirming this issue.

**Comment by sedwards2009** [comment]
only took 2 years

**Comment by WillPlatnick** [comment]
@sedwards2009 I can confirm this behavior in 0.38.1 as well. If I don't source the script, ctrl+L works as I expect and flushes the buffer. With the command script active, everything remains in the buffer.
