### ISSUE TITLE
User Themes button in Settings does nothing on MacOS HS

### ISSUE THREAD

**Issue by matrixraven** [sedwards2009/extraterm#151]
Installed on MacOS High Sierra.
I go into settings, and click appearance, then User themes button with the folder icon, expecting to be able to browse the directory and add some iTerm2 themes I have on hand.
It does nothing. Doesn't open in Mac Finder, or show anything else.

**Comment by sedwards2009** [comment]
I should open that folder in the finder for you. Clearly a bug somewhere.

**Comment by sedwards2009** [comment]
This will be in 0.41.
