### ISSUE TITLE
Can anti-aliasing be disabled?

### ISSUE THREAD

**Issue by nigels-com** [sedwards2009/extraterm#152]
I'm setting up a new machine, a bit less focused on getting things done day to day.

I did this quick comparison of text legibility in `extraterm` vs `terminator` vs `xterm`

I'm feeling like there is some merit to pure bitmap (non anti-aliased) mono-spaced terminal text.

Thing is, will electron and/or chrome even let you turn off smoothing?

![screenshot from 2019-01-08 16-05-49](https://user-images.githubusercontent.com/545677/50812814-e2d5e400-135f-11e9-83c1-9484d3847507.png)

**Comment by sedwards2009** [comment]
There are some basic knobs and levers which can be played with to change the text rendering. But I want to give this issue some attention only after I've written my own canvas and font atlas based renderer for the terminal screen.

**Comment by sedwards2009** [comment]
Using the canvas API and drawing there are very few ways of controlling anti-aliasing, even less than in normal CSS. That said, I've got some ideas on making  a pixel level contrast filter of sorts which could cut out a lot of the "halos" you sometimes see on text when the font size and device pixels don't align very well. (I see this happening the most with bold text.)

I'm not against bitmaps fonts. The new canvas/font atlas rendering approach could accommodate them. The biggest problem is that I'm just not aware of any modern bitmaps fonts which come in big enough sizes for today's screens.

**Comment by sedwards2009** [comment]
Text in v0.53.0 will now use subpixel AA when possible which should improve quality and at least bring it to the same standard as other apps.
