### ISSUE TITLE
Quake mode doesn't preserve window size nor position when minimize to tray is enabled

### ISSUE THREAD

**Issue by zakius** [sedwards2009/extraterm#153]
Basically what title says, I'm using latest release (0.40.0) on Windows 1809

**Comment by sedwards2009** [comment]
Is the window full size?

I've seen at least one window positioning problem on Windows which seemed to be related to full screen windows.

**Comment by zakius** [comment]
Yeah, after testing few more things it's just the maximized state that is not preserved, sorry for the confusion

**Comment by sedwards2009** [comment]
Related to #120

**Comment by zakius** [comment]
I'm not sure if I should comment on this or open new issue but it's heavily related:

currently it may seem that maximized size is preserved but actually *restored* size is shown first and only then maximized back, it's clearly visible if *full terminal* app is running as it renders in smaller size first and then accommodates to maximized window

**Comment by sedwards2009** [comment]
I tried that out today on Windows and it seemed fine. I'll test it a bit more and also try out Linux/macOS. thanks
