### ISSUE TITLE
Renaming of tabs

### ISSUE THREAD

**Issue by Redirts** [sedwards2009/extraterm#157]
One feature I miss in extraterm when compared with ConEMU/Cmder is the possibility to rename the title on tabs by right clicking on the tab.

Is this on the horizon or already possible and I just could not figure it out?

Thanks

**Comment by sedwards2009** [comment]
That feature is not in there yet. I'll add it to the roadmap. #30

**Comment by v-v** [comment]
Related to tab renaming, I'd love the possibility of assigning colors to tabs in a similar ways as in iTerm2 where you can just right click a tab and select a quick color. (The active tab title is completely of the selected background color while the others tabs just display a line under the title of the assigned color - if there is one). This allows to easily recognize and group the tabs when there are more of them open.
Thanks for the great work so far!

**Comment by sedwards2009** [comment]
Keeps the ideas coming. With Extraterm I'm also working towards having an extension/plugin system which would allow for all kinds of customisation such as how tab title should work.

**Comment by sedwards2009** [comment]
This was made possible in v0.43.

**Comment by krzysztof-callstats** [comment]
I am not sure if this is a request or I just can't find how to do it. Is it possible to show the current path in the tab name? I tried something like `${term:path}` but without luck. It would be very helpful as default name as right now all my tabs are named the same and I don't even rename them anymore because every time I close extraterm the session is lost anyways.

**Comment by sedwards2009** [comment]
@krzysztof-callstats  Making the tab title format configurable where the session is configured, is planned at some stage.

By default, you should be seeing the current directory of your shell in the tab title. Are you also using the shell integration?

**Comment by krzysztof-callstats** [comment]
@sedwards2009 yes, I am using shell integration for zsh, and my default tab name is `zsh` with some keyboard icon

**Comment by krzysztof-callstats** [comment]
Is it a bug or expected behaviour?
