### ISSUE TITLE
Misaligned app buttons

### ISSUE THREAD

**Issue by MrARC** [sedwards2009/extraterm#159]
Hello, today i replaced hyper with extraterm (i feel your terminal is faster), thanks for developing this.

I found some weird behaviour with the close, minimize and menu buttons, you need to hover the mouse in a very specific place of the box to be able to click the button, otherwise if you hover the mouse over the icon (the pseudo ::before element containing the icon) it won't work

EDIT: this only happens if you have the Windows title bar option in "Theme", using "Compat theme" doesn't have this issue

![image](https://user-images.githubusercontent.com/4296205/51509985-6956e080-1db8-11e9-87dc-53fa7ff8235e.png)

I don't know if this issue is specific for windows, i'm using the lastest version of extraterm (version 0.40.0)

**Comment by Kynolin** [comment]
I get the same issue on Windows 10 with theme and have been using compat theme. I also noticed today that the menu/minimize/maximize/close buttons will be hidden behind the shell tabs if you have a few open and resize the window to where the tabs take up the entire width of the title bar.

![image](https://user-images.githubusercontent.com/540218/53655748-b24f4f80-3c16-11e9-9c27-22b3286cd646.png)

**Comment by sedwards2009** [comment]
@Kynolin That is a different issue. I noticed it too.

**Comment by sedwards2009** [comment]
@MrARC Fixed in version 0.41.
