### ISSUE TITLE
support for bash_it

### ISSUE THREAD

**Issue by spkane** [sedwards2009/extraterm#161]
I use the bash_it (https://github.com/Bash-it/bash-it
) framework for managing bash plugins/themes and it doesn't quite play nice with the setup script for ExtraTerm (https://github.com/sedwards2009/extraterm), mostly because they both define some of the same post/pre functions.

I've been playing with it a little bit, but am still having issues getting them to play 100% nicely together. That being said, I don't think it would be too hard, just might require some small changes to both.

If I figure out a basic working example, I'll post it here, but I'd love some other eyes on it, if anyone feels inspired.

**Comment by spkane** [comment]
https://github.com/Bash-it/bash-it/issues/1319

**Comment by spkane** [comment]
It looks like some work is being done in bash-it to also fix some issues that have cropped up for some iTerm users. https://github.com/Bash-it/bash-it/pull/1304

It appears that some smart terminals and bash-it are using the post/preexec functions is different ways, and some of them have older code, etc. Apparently this repo is considered the core one for these functions (and may get pulled into bash-it, if testing works well).

https://github.com/rcaloras/bash-preexec

**Comment by nwinkler** [comment]
@spkane Can you give the https://github.com/Bash-it/bash-it/pull/1304 PR a try, please? Maybe you can report back here or on the https://github.com/Bash-it/bash-it/issues/1319 issue with feedback whether it made a difference...

**Comment by sedwards2009** [comment]
I assume that @spkane closing this issue means that the problem has been fixed up by bash-it.

**Comment by spkane** [comment]
Honestly I don't know, but I haven't been in a position to test this in a long time, so I went ahead and closed it so that it wasn't sitting open. It can always be re-opened is someone runs into it again and wants to dig into it.
