### ISSUE TITLE
Crash and Errors after long running process

### ISSUE THREAD

**Issue by nicholasfoden** [sedwards2009/extraterm#162]
I left extraterm running a script with a decent amount of output. After about a day's worth of history, Extraterm crashed, but the child processes running in the background didn't thankfully. 

Extraterm would not restart until all the child processes were killed and showed this error
![image](https://user-images.githubusercontent.com/23345512/52281938-1acc4900-2957-11e9-8309-76368facc70e.png)

**Comment by sedwards2009** [comment]
There error pop up is because the first Extraterm is still running (kind of), and you can't run multiple instances at once.

Were you running cmd.exe or PowerShell?

**Comment by nicholasfoden** [comment]
I was running cmd.exe 
Windows 10 Pro x64 1803

**Comment by sedwards2009** [comment]
I've fixed a bunch of memory problems in 0.44.1. This situation should be much better now.

I've still got some optimisation ideas on reducing the memory requirements of text in the scrollback, but for now I'll considered this issue fixed.
