### ISSUE TITLE
Ctrl+C in PowerShell

### ISSUE THREAD

**Issue by mdoulaty** [sedwards2009/extraterm#163]
I'm using version 0.40.0 on Windows 10 (build 17763.253), on PowerShell, Ctrl+C key combination doesn't work (the expectation is to cancel the current command and return). Is there a workaround?

![term](https://user-images.githubusercontent.com/3152752/52426683-b2b86700-2afe-11e9-90e0-62835d457bcf.gif)

**Comment by sedwards2009** [comment]
I can see this too. It's certainly annoying.

**Comment by sedwards2009** [comment]
Related issue in node-pty which Extraterm uses. https://github.com/Microsoft/node-pty/issues/7

**Comment by sedwards2009** [comment]
This problem will be most likely fixed after the next big Windows 10 update later this year. Then Extraterm (actually node-pty) will be able to use the new ConPTY infrastructure in Windows which will solve a heap of related issues like this one.

**Comment by sedwards2009** [comment]
Hopefully fixed in node-pty. https://github.com/Microsoft/node-pty/pull/287

**Comment by mdoulaty** [comment]
Thanks, closing the issue. Works as expected now.

**Comment by sedwards2009** [comment]
great!
