### ISSUE TITLE
Select Tabs via Keybinding

### ISSUE THREAD

**Issue by deg0nz** [sedwards2009/extraterm#166]
I did not fond this function in extraterm's keybindings or an issue about this:

I want to switch between tabs with a keyboard command. For example:
`Alt+Leftarrow` Selects the next left tab or `Alt+Rightarrow` selects the tab to the right.
Is this possible somehow? If not, this is a feature request :)

Thanks a lot and greetings

**Comment by sedwards2009** [comment]
This does already exist. You can find it in "Keybindings" settings under "Focus Tab Left/right". On Windows/Linux it is Ctrl+, and Ctrl+. by default.

**Comment by deg0nz** [comment]
Alright! It's working, thanks. I was a little bit confused by the naming, but is makes sense. thanks a lot!

**Comment by sedwards2009** [comment]
If you can come up with a better name, I'm happy to hear it.
