### ISSUE TITLE
Pasting text containing LF or CRLF behaves differently in different shells.

### ISSUE THREAD

**Issue by Kynolin** [sedwards2009/extraterm#167]
When pasting a block of text containing LF characters into a WSL instance, it works as expected. When pasting the same block of text containing CRLF characters, it will paste a blank line in between every line that was copied. I noticed this inside a python session, because it breaks the indentation when pasting. The opposite happens in a CMD session. Pasting CRLF works normally, and pasting LF will paste all the lines into one line.

To reproduce the issue, I just had a block of echo commands in VS Code, and I switched between LF/CRLF when copying and pasting.

I would guess the fix for this issue would be similar in nature to #103 and #164.

**Comment by sedwards2009** [comment]
It sounds like more care needs to be taken when processing CR and LF chars. Extraterm should autodetect the line ending and paste the right number of 'enter' key presses.

**Comment by sedwards2009** [comment]
Issue #103 is a very different issue, BTW.

**Comment by sedwards2009** [comment]
Fixed in 0.41.1.
