### ISSUE TITLE
paste text always adds extra line breaks

### ISSUE THREAD

**Issue by jyhnnhyj** [sedwards2009/extraterm#168]
when I paste a multi-line inside any text editor, i.e. vim, it always adds extra line breaks (empty line after each line).
The original text has \n line endings and when I do the same using another terminal emulator, it works as expected. Is there a config that I'm missing for this?

**Comment by sedwards2009** [comment]
related to issue #164

**Comment by sedwards2009** [comment]
related to issue #167

**Comment by sedwards2009** [comment]
Fixed in 0.41.1.

**Comment by jyhnnhyj** [comment]
I just tried 0.41.1 on Windows 10 and experienced something a bit strange
so when I copy from VS Code editor (which has LF line endings) and paste inside vim running in extraterm, it add the extra line breaks again - but when I paste the same text in notepad++ (and see only LF line endings), then copy from notepad++ and paste in vim in extraterm, it's okay this time.

also for any piece of text that I copy from chrome webbrowser, when I paste, it again adds extra line breaks. Is this expected?

**Comment by sedwards2009** [comment]
0.41.1 isn't released yet. You are probably looking at 0.40.0.

**Comment by jyhnnhyj** [comment]
I tested on 0.41.0 (https://github.com/sedwards2009/extraterm/releases/download/v0.41.0/extraterm-0.41.0-win32-x64.zip)

okay then will wait for 0.41.1 

Thanks for the quick fix 👍

**Comment by sedwards2009** [comment]
sorry for the confusion there.
