### ISSUE TITLE
Feature Request : Highlight Keywords in outputs

### ISSUE THREAD

**Issue by ChicK00o** [sedwards2009/extraterm#169]
Well when long running logs are on, keywords like "error", "warning", "panic", "exceptions" getting highlighted as the logs are being scrolled by would be a great thing.
Then additionally having, the ability to set the keywords, its highlight colour would be the icing
If you can put in time to explain the new refactoring, and your idea of plug-ability of extraterm would be great

**Comment by sedwards2009** [comment]
A long time ago I used a text editor called jEdit. It had one feature which I found extremely useful and hadn't seen anywhere else. You could have multiple searches and highlights active at the same time, with different colours. I used this feature a lot for analysing log files from servers. This is the vision I have for the search feature but I'm postponing it until other more requested and basic features are in. There is also a certain amount of work to be done internally to support multiple highlights. But that is a feature I want.

Your last question is a big one. It will take a fairly big blog post to explain the direction there. The important thing to know is that I'm constantly working to expand the internal plugin API and trying to put as much new functionality into plugins (called 'extensions'). The `extensions/` folder in the code is the current set of things implemented as plugins/extensions.
