### ISSUE TITLE
Command line start up options and flags don't work correctly from the packaged binaries

### ISSUE THREAD

**Issue by sedwards2009** [sedwards2009/extraterm#17]
Starting up extraterm from a binary zip download and passing in some flags and options (e.g. `--cygwinDir`) doesn't parse the options correctly.

The problem is in the `commander` module which Extraterm uses to parse command line arguments. It assumes that the first two items in `process.argv` are the nodejs executable and then the name of script being executed. This assumption is violated when starting up the packaged version of Extraterm.

A workaround is to pass an extra dummy value before the first flag or option. i.e. `extraterm.exe XXX --cygwinDir c:/foo`

**Comment by sedwards2009** [comment]
See issue https://github.com/tj/commander.js/issues/512

**Comment by sedwards2009** [comment]
Fixed in b08eeab9f6533320241b4bce2ea0dda37a4b75ce

**Comment by Tympanix** [comment]
I would assume this is a quick fix? I would love to see a universal solution that not only works with Electron but in general. You mention in [#512](https://github.com/tj/commander.js/issues/512) having two _parse_ functions. I would like to give that a +1.
