### ISSUE TITLE
memory usage issues

### ISSUE THREAD

**Issue by jyhnnhyj** [sedwards2009/extraterm#170]
I now switched to this wonderful terminal for all my workloads, well done the author(s)!
I usually have some watch / htop sessions running on 2,3 tabs 
the issue that i'm facing, is that after a few hours (~4-5) with 5 tabs, 2,3 of them have some watch commands, the memory usage of the extraterm is above 3.5 GB, it becomes super slow and usually blanks out and I have to restart - after launching again, the fresh one works just well (for a few hours)
possible memory leak? 
I suspect it somehow keeps the coming data to the terms and at some point it gets out of control
I'm on Windows, using v0.41.0

**Comment by sedwards2009** [comment]
This sounds related or the same as #162

**Comment by sedwards2009** [comment]
I've fixed a bunch of memory problems in 0.44.1. htop and cmatrix don't bloat up the memory now. Also closing tabs releases memory correctly too.

Re-open or create a new issue if other ways of blowing up the memory are found.
