### ISSUE TITLE
Extraterm doesn't respect the title change request

### ISSUE THREAD

**Issue by j4hangir** [sedwards2009/extraterm#172]
In respect to #157, in other terminals when using ZSH, the title of the program will be changed to the opened program, which serves as a neat trick for re-finding the window of interest amongst others; that also reminds one of the need for a `multi-instance` support as has been requested here #115.

**Comment by sedwards2009** [comment]
When using `fish` Extraterm certainly does catch and use the window title escape code to set the tab title.

**Comment by sedwards2009** [comment]
Under which terminal emulator did you see the title change for zsh?

I see that this happens in Konsole. It is because Konsole digs into the process info from the OS and extracts the app name from there. I don't really want to do that in Extraterm. It is very OS specific and buggy.

**Comment by j4hangir** [comment]
> Under which terminal emulator did you see the title change for zsh?
> 
> I see that this happens in Konsole. It is because Konsole digs into the process info from the OS and extracts the app name from there. I don't really want to do that in Extraterm. It is very OS specific and buggy.

Under **iTerm 2** with Mac OS. I use the same exact setup under Mac and Windows with the only difference of using Extraterm and iTerm.

**Comment by sedwards2009** [comment]
I'm not going to implement what Konsole and iTerm2 is doing to probe the operating system for the name of the running executable.

To get the same functionality (and more) I suggest you set up the Extraterm's terminal integration. If you don't like the frames all over the place then you can configure that in the Settings tab. Without the frames being on you should still see the tab title change.
