### ISSUE TITLE
Feature request: link detection

### ISSUE THREAD

**Issue by zakius** [sedwards2009/extraterm#173]
It would be handy if it was possible to detect links in displayed text and make them clickable (probably with some toggle button, often `ctrl` key is used for that)

while doing that please make sure that links ending with `)` are handled properly (in most cases libraries cut off this character making the address incorrect, and addresses like this are quite often used on Wikipedia for example)

**Comment by zakius** [comment]
Maybe https://alexcorvi.github.io/anchorme.js/ will come handy in this as it seems to cover all use cases

**Comment by sedwards2009** [comment]
I won't be able to use that directly but it could be interest to look at how it detects all of the different styles and types of links.

**Comment by sedwards2009** [comment]
Released in v0.57.0.
