### ISSUE TITLE
Ctrl-left, ctrl-right (arrow keys) don't work in ZSH, but work perfectly fine in Bash.

### ISSUE THREAD

**Issue by j4hangir** [sedwards2009/extraterm#176]
The expected behavior is to do forward-word and backward-word.

**Comment by j4hangir** [comment]
It's worth mentioning, using the Bash terminal and sourcing the same exact `.zshrc` results in the expected behavior.

**Comment by sedwards2009** [comment]
Are you on Linux? I just tried this and it works fine for me on Linux.

**Comment by accountgit** [comment]
Just tried in linux with bash and works correctly, but if i try the same inside a screen or tmux session don't work.

**Comment by sedwards2009** [comment]
I can confirm the problem with bash running inside screen.

**Comment by krzysztof-callstats** [comment]
I have the same problem on Mac

**Comment by sedwards2009** [comment]
Released in 0.42.0.

**Comment by j4hangir** [comment]
The problem is still there is back in 0.42.2
