### ISSUE TITLE
Linux and bash image do not show up

### ISSUE THREAD

**Issue by 00sapo** [sedwards2009/extraterm#177]
In Linux with bash, you can't get `show` to work properly with images and, after its call, something is wrong with commands which redraw the wall screen (such as `vim` or `top`) until the `show` frame is not removed.

Example created with empty `~/.bashrc` and `/etc/bash.bashrc`:
![Peek 2019-04-03 01-34](https://user-images.githubusercontent.com/22996003/55443013-5aa75980-55b1-11e9-9da3-fc2390866a98.gif)

**Comment by 00sapo** [comment]
The same happens with zsh

**Comment by sedwards2009** [comment]
You're right. I'm seeing the problem here too.

**Comment by sedwards2009** [comment]
In 0.41.3.
