### ISSUE TITLE
Double click on text

### ISSUE THREAD

**Issue by accountgit** [sedwards2009/extraterm#178]
When you have a path and you double click on it, only is selected one part of it.
Example: 
/etc/passwd <- if you double click over the "w", only is selected "passwd", could be selected all "/etc/passwd"

In Konsole there is a setting that allows configuring the characters considered part of a word when double clicking, with the default value of ':@-./_~?&=%+#'.

**Comment by sedwards2009** [comment]
This is probably one of the easier things to change. I'll probably change it to match Konsole. I don't see a reason to make it configurable though.

**Comment by sedwards2009** [comment]
Released in 0.42.0.
