### ISSUE TITLE
trim file size down.

### ISSUE THREAD

**Issue by farfromrefug** [sedwards2009/extraterm#18]
The app  size on osX is huge.
it could literally be 300% smaller.
The issue is in the electron framework where you don't preserve symlinks while packaging
https://github.com/atom/electron/issues/2003

**Comment by sedwards2009** [comment]
Thanks. I saw that the OSX zip was much bigger but haven't had the time to dig into the problem. It does look like a simple case of zip not handling the symlinks and should be easy to fix.
