### ISSUE TITLE
Feature Request: Transparency

### ISSUE THREAD

**Issue by jwhipp** [sedwards2009/extraterm#181]
This is a feature request to handle background transparency, preferably with configurable levels of opacity.   In Hyper on Windows, this is achieved with a plugin, some other terminals (ConEMU) it's just native.    A similar feature in Extraterm would be amazing.

**Comment by sedwards2009** [comment]
Duplicate of issue #66

**Comment by jwhipp** [comment]
Apologies for the duplicate, for some reason, I didn't get added as a watcher to #66 and totally forgot it about it.
