### ISSUE TITLE
Feature request: Working directory setting for shell

### ISSUE THREAD

**Issue by dacame** [sedwards2009/extraterm#184]
Hi guys!

I am using Extraterm 0.41.4 in macOS Mojave in my MacBook Pro and on Chrome OS 73 in my PixelBook. They are working great most of the time, but I've realized on the macOS version that the shell opens using the initial working directory from the root path "/". In the PixelBook starts in $HOME, and that is ok.

I think it would be great to have an option in "Settings" to be able to select the working directory you want to open from the beginning, as you can for example in iTerm in Mac.

Great job BTW!

Thank you!

Best regards,
David.

**Comment by sedwards2009** [comment]
Released in 0.42.0.
