### ISSUE TITLE
Copy and paste doesn't work in the search panel

### ISSUE THREAD

**Issue by krzysztof-callstats** [sedwards2009/extraterm#185]
In the newly introduced search functionality (which I am grateful for!) the copying and pasting doesn't seem to work at all. 

I'm on `macOS Mojave version 10.14.4` using `Extraterm version 0.41.0`. I am using ZSH but I doubt it matters in this case.

**Comment by sedwards2009** [comment]
This works fine on 0.41.4 Linux. I could be macOS specific.

**Comment by sedwards2009** [comment]
This problem also affected all input fields in the app when running on macOS.

**Comment by sedwards2009** [comment]
Released in 0.42.0.

**Comment by krzysztof-callstats** [comment]
> Released in 0.42.0.

Thank you!

> This problem also affected all input fields in the app when running on macOS.

Was this fixed as well? I've tried `0.42.0` as soon as it was available, and copy-paste (with keyboard shortcuts) works fine, but I still can't open the context menu, nor use other shortcuts (like select-all).
