### ISSUE TITLE
Bug: If using argument in default shell, Extraterm does not open anymore (macOS)

### ISSUE THREAD

**Issue by dacame** [sedwards2009/extraterm#186]
Hi guys,

If using an argument in the default shell settings (for example --login or --init-file <my bash_profile>), the shell is not opening and then extraterm is not able to initialize.

I suppose there is a config file to change this in order to make my Extraterm working again.

My OS is macOS Mojave 10.14.4 and Extraterm version 0.41.4.

I think that the expected behavior from Extraterm should ignore arguments and be able to open if those cannot be interpreted.

Thank you guys for the amazing job.

Cheers.

**Comment by dacame** [comment]
To change back my configuration I only needed to edit `extraterm.json`:

```
$ vim ~/Library/Application\ Support/extraterm/extraterm.json
```

And deleting **args**, like following:
```
[...]

"sessions": [
    {
      "args": "",
      "name": "Default shell",
      "shell": "/bin/bash",
      "type": "unix",
      "useDefaultShell": true,
      [...]
    }
[...]
```

**Comment by dacame** [comment]
Interesting behavior is that if I use `-l` instead of `--login` in arguments, then it works. According to bash man page, `-l` and `--login` should be the same.

Using Extraterm in my other laptop (Pixelbook with Crostini), the argument `--init-file` works well, but `-l` or `--login` does not work either. So seems to not be consistent depending on the OS where shell (bash in both cases) is used. Maybe to consider this from configuration screen/file?

Hope this helps to understand better the usage of arguments in shell configuration.

**Comment by sedwards2009** [comment]
Version 0.49.2 should now pause and let you see the error message in the case that the shell doesn't start up.
