### ISSUE TITLE
Support selection among multiple WSL versions

### ISSUE THREAD

**Issue by Krantz-XRF** [sedwards2009/extraterm#188]
I had multiple versions of WSL installed, and when I am in `cmd`, I can use `wsl {GUID} ~` or `bash {GUID} ~` to choose a desired version of WSL to launch, but when I add that parameter (`{GUID} ~` or `{GUID}`) to `Arguments`, that tab will not launch properly.

I can, however, use the `Windows console session` method (with `Executable=wsl.exe` and `Arguments={GUID} ~`), but then the shell integration is not supported anymore.

Where should I provide this `{GUID}` or something else to select the correct WSL version?

**Comment by sedwards2009** [comment]
This was feature was added to the session settings page a few releases ago.
