### ISSUE TITLE
Can't copy and paste in terminal anymore

### ISSUE THREAD

**Issue by Chagui-** [sedwards2009/extraterm#190]
In 0.42, cant copy and paste into terminal anymore. 
In 0.41.3 i could by using ctrl+shift+c and shift+insert. 

Context menu doesn't show the option either.
![image](https://user-images.githubusercontent.com/3289167/57172763-71301300-6df2-11e9-8e9f-9e7da10074a3.png)

**Comment by sedwards2009** [comment]
Which operating system are you using here?

**Comment by sedwards2009** [comment]
I'm seeing this too on Linux.

I also discovered that `fish` automatically supports `xsel` for pasting from the clipboard. This initially masked the bug for me by making it look like Ctrl+V still works when it didn't. Ouch!

**Comment by sedwards2009** [comment]
Just fixed in the 0.42.1 release. Thanks for reporting.
