### ISSUE TITLE
Keyboard shortcuts not working for macOS

### ISSUE THREAD

**Issue by krzysztof-callstats** [sedwards2009/extraterm#191]
I suppose this is the side effect of #185.

On macOS, the shortcuts (like cmd+C, cmd+V) now work only in the search field, but not in terminal (where they used to work). And then there are shortcuts like cmd+A (select all) which work neither in the terminal, nor in the search field.

I'm on macOS Mojave version 10.14.4 using Extraterm version 0.42.0.

**Comment by krzysztof-callstats** [comment]
I think it is a duplicate of #190, sorry!

**Comment by sedwards2009** [comment]
@krzysztof-callstats  Try on the 0.42.1 version. That may fix the copy and paste keys.

**Comment by krzysztof-callstats** [comment]
It did, thank you
