### ISSUE TITLE
(doc/help) Add note about customizing keybindings

### ISSUE THREAD

**Issue by Mekk** [sedwards2009/extraterm#193]
I just found extraterm and learn it. Thank you, fresh and interesting approach to the old problem.

Now about the problem: for two hours I was thinking that it is impossible to customize keyboard shortcuts (and that this is not implemented yet feature).  This is because while using one of the default keybindings, settings window simply doesn't allow to edit keys, period. I clicked Record key but this only helped to look for command using this key. I tried clicking and doubleclicking various things, nothing happened. I noticed there is ```.config/extraterm/keybindings``` directory but had no idea what to store there. Found how to do it by pure accident.

So I suggest the following (maybe both):

1. Please add to the User Guide (maybe to existing "Keyboard Shortcuts" section) sentence like 

    > Default keybindings are not editable. To customize keyboard shortcuts you must create your own keybindings set first – visit Settings/Keybindings, pick one of the default configurations, click Duplicate icon positioned right to the dropdown, click Rename icon to name the configuration to your taste. This will make it possible to edit keybindings for all the commands.

2. In case user is using one of the default sets, consider adding note like

    > Keys editing disabled (standard keybindings set in use). Click [[]] icon to create editable keybindings set.

    in Settings/Keybindings window (mayhaps below the title, in red italic).

    Or leave [+] [x] icons for key editing active and popup info "keybinding editing disabled for standard set, create your own set via clicking [[]] icon to edit keybindings".

    Or sth like that

3.  … Or, maybe just let me edit keybindings for default set. Technically, simply silently duplicate the set under the hood once I edit any keybinding (and let saved set shield official one in case the name matches)?

**Comment by sedwards2009** [comment]
Thank you for taking the time to give this detailed account of this problem. This is quite a poor situation. I like a lot of your suggestions though.

What I'm going to do is:

* update the User Guide like you said
* show the + - buttons always but disabled if changes aren't allowed.
* Change the little hover tip thing on the + - buttons to something like "Duplicate this configuration to edit it".
* Add text to the current duplicate icon at the top. i.e. add "Duplicate".
* Maybe add a hover tip to the wide dropdown at the top to encourage people to duplicate first, or at least explain that built in configs can't be changed directly.

thanks again for this excellent UX bug report. If you encounter anything else like this, or even smaller problems please report them. I'm used to how Extraterm works and it makes sense to me, so I will miss a lot of problems which are obvious to others.

**Comment by Mekk** [comment]
Is it possible to use icons in hover texts? If so, just adding the icon to the suggestion would do (without the necessity to label the icon and spend space this way)

Or maybe instead of disabling [+]/[-] make them popup „You are editing standard configuration. Would you like to duplicate it?” ?

Still, this is fine-tuning. Your first 3 points would do.

**Comment by sedwards2009** [comment]
The hover text as implemented right now only allows text. (It is really just using an existing HTML feature.) I could make my own hover thing but that is a lot more work.

I'm first going to try a hover type text on the [+]/[-] buttons and see how that feels.

**Comment by sedwards2009** [comment]
Fixed in v0.42.2
