### ISSUE TITLE
Framing or not depending on the command output size

### ISSUE THREAD

**Issue by Mekk** [sedwards2009/extraterm#194]
Minor extraterm annoyance: while I like those frames and enjoy them (especially that they make command status so visible), I feel my terminal is sometimes a little *filled* when I issue a few commands with short output, like ```pwd``` or ```date```. I blacklist them in Settings, but this is somewhat cumbersome, and it turns out there are more of them than I expected.

What about an option like
```
[x] Don't frame commands with single-line output
```
or maybe a bit more fine-tuning of this kind (set minimal number of lines to get the frame, treat this option differently depending whether command succeeded or failed…).

In general this is about possibility to have some *wider* rules when to use frames, and when not instead of limiting to simple names.

PS This can also help in case of multicommands like ```git``` or ```hg```. I want frame for ```hg status```. I don't want it for ```hg id```

**Comment by sedwards2009** [comment]
Added in v0.46.0.
