### ISSUE TITLE
How to scroll with mouse within application that supports it?

### ISSUE THREAD

**Issue by MostHated** [sedwards2009/extraterm#196]
Hello,
    I often use [Micro as my editor](https://micro-editor.github.io) which allows you to scroll up and down with the mouse wheel within the editor, but when I do in ExtraTerm it doesn't scroll within Micro, it scrolls Micro out of the way and goes up to previous terminal buffer. Is it possible to toggle or change this action when need be? I tried looking through the settings, but I didn't happen to see anything that stood out as to what I was after.

Thanks,
-MH

**Comment by sedwards2009** [comment]
I can reproduce and confirm this. It works correctly in Konsole, but not Extraterm.

**Comment by Chrismarsh** [comment]
Also see it trying to scroll back a tmux buffer, or vim

**Comment by tkapias** [comment]
I just switched from Mobaxterm to extraterm+WSL and after 24 hours it's also the one thing that strikes me, I can't scroll in nano. You can live without it, but it was so comfortable. 

Is there some update on this ?

**Comment by sedwards2009** [comment]
I've got working code now which supports scrolling with the mouse wheel inside `micro`. I'll test it in `nano` too. This will be in the next Extraterm release.

**Comment by sedwards2009** [comment]
Released in 0.45.0.
