### ISSUE TITLE
Command hints not being rendered in tips

### ISSUE THREAD

**Issue by DanCouper** [sedwards2009/extraterm#199]
Version: v0.42.1
OS: MacOS 10.14.3

Not a massive thing, but the hints for commands aren't being rendered out, I just get blank space where they should be:

<img width="527" alt="Screenshot 2019-05-30 15 07 43" src="https://user-images.githubusercontent.com/573694/58638546-07216580-82ed-11e9-9276-153bda55955f.png">

> Enter cursor mode using .

Which is assume should be 

> Enter cursor mode using `Ctrl+Shift+Space`.

Or similar

**Comment by sedwards2009** [comment]
I see the problem here too. thanks.

**Comment by sedwards2009** [comment]
Fixed in v0.43.0.
