### ISSUE TITLE
ssh sessions / profiles / speed commands

### ISSUE THREAD

**Issue by Leen15** [sedwards2009/extraterm#202]
Hi,
finally I found a terminal with working split panels & tabs!
There is one simple thing that I cannot find in this great app.
Is there a way to add a shortcut to a ssh session? a profile or a list of speed commands for start a new shell with an ssh instance?
I tried the session types but I cannot understand how they work if I want to start a session with a specific command (an ssh login in my case).

Thanks

**Comment by sedwards2009** [comment]
What you want is a session configured which runs the command `/usr/bin/ssh` as the 'shell' and passes the hostname of where you want to go as it's arguments. On Linux you just use the normal "unix session type" and configure it.

You can use this new session by either using the right mouse button / context menu, on the + button in the tab bar, and then selecting the session you want. You can also access your session via the command palette and searching for it.

Your new session type will also appear on the keybindings tag in settings. There you can duplicate the keybindings and then edit them by assigning a shortcut.

**Comment by Leen15** [comment]
Does it work also on mac OS?

**Comment by sedwards2009** [comment]
It should. In a terminal run `which ssh` to find out exactly where the `ssh` exe is on macOS. The rest should be the same.

**Comment by Leen15** [comment]
Sorry @sedwards2009 , did you try it?
I'm trying with a setup like:
shell: `/usr/bin/ssh`
args: `-J root@myhost  -i ~/.ssh/id_rsa`

But it asks anyway for a host password.
if I try from a shell with a simple `ssh root@myhost` it works...

**Comment by sedwards2009** [comment]
Expand `~/.ssh/id_rsa` to the full path to our home folder. The arguments are not passed through a shell command parser, so things like `~/` don't work.

**Comment by Leen15** [comment]
Already tried but nothing changed :(

**Comment by Leen15** [comment]
I'm not sure that I can pass the host in an arg, but if I put it in the same field it doesn't work:
shell: `/usr/bin/ssh`
args: `-i /Users/myuser/.ssh/id_rsa root@myhost`

**Comment by Leen15** [comment]
Ok I found another way.
Shell: `Default login shell`
args: `-c "ssh root@myhost;$SHELL"`
