### ISSUE TITLE
"Show and focus" how key will show the window but not properly focus

### ISSUE THREAD

**Issue by MostHated** [sedwards2009/extraterm#203]
Hey there, one thing that bugs be but I just always forget to mention is, I use the "Show and focus" hotkey constantly, but when I do it simply shows the window but doesn't properly focus it, I have to click on it to begin typing. Alt-tabbing to the window works just fine, but not via hotkey. Is there something I can do, either in the terminal or within my OS to make it so that when I hit the hotkey it properly focuses so I can just start typing straight away?

Pop_OS : 19.04 
Extraterm : 0.42.2 

P.S. is there any way to have automatic update checking for Extraterm? I had simply downloaded it, put it in a folder, and created an OS shortcut to initially open and use it. The releases are a few months old now though.

**Comment by sedwards2009** [comment]
fixed in v0.43.0.

**Comment by MostHated** [comment]
Great news. I tried it out and it is working just as I expected. Much appreciated!
