### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by MostHated** [sedwards2009/extraterm#204]
Hey there,
    I keep seeing that things get pushed to master with fixes, changes, etc, but the builds under Releases have not been updated since May, so I have been using that build ever since. Is there a proper way to keep my client up to date? I tried to look around and saw there was a link, but the link unfortunately gave this message:

```
UserProjectAccountProblemUser project billing account not in good standing.The billing account for project 361789388735 is disabled in state closed
```
Is there a way to use a package manager to keep my client up to date, or what is the recommended way?

Thanks,
-MH

**Comment by sedwards2009** [comment]
There was a problem with the downloads up on google cloud. Thanks for telling me.

The nightly builds are only updated when master is changed. I only moved a heap of stuff from a branch onto master yesterday. The downloads should automatically update in the next 24 hours.

Those downloads are just automatically built from master. They may be completely broken. The releases via the website and github are some what better tested.

I don't provide an automatic way of keeping Extraterm up to date right now. It is possible that someone is making packages of Extraterm which you can install via a package manager. Then you should have something which updates some what automatically.
