### ISSUE TITLE
Nerd Font renders only half of an icon in some cases

### ISSUE THREAD

**Issue by vasiby** [sedwards2009/extraterm#205]
Font used "Hack NF" (Hack font complete windows compatible)
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack/Regular/complete

Here's the comparison of the same font as it's displayed in the new Windows Terminal and Extraterm, as you can see Extraterm  cuts some icons in half. (oh-my-zsh with Powerlevel9k theme in WSL)

![image](https://user-images.githubusercontent.com/53339460/62717702-0e5fa080-ba0d-11e9-8030-2f4c93feef7b.png)

**Comment by sedwards2009** [comment]
This is a duplicate of issue #77 .

**Comment by sedwards2009** [comment]
This is a duplicate of issue #77 .
