### ISSUE TITLE
Update 0.44.0 contains still version nr 0.43.0

### ISSUE THREAD

**Issue by suschizu** [sedwards2009/extraterm#207]
hello!
I just noticed that the latest version of extraterm still shows 0.43.0 as version
<img width="389" alt="Screenshot 2019-08-26 at 20 54 26" src="https://user-images.githubusercontent.com/16004333/63715370-ec0ab700-c843-11e9-9806-63d7915d39ed.png">

**Comment by sedwards2009** [comment]
That is a bit embarrassing. thanks. It will be fixed in the next release.

**Comment by suschizu** [comment]
great - thanks ;)
