### ISSUE TITLE
version numbers of 'extraterm' 0.44.0 are incorrect on macOS

### ISSUE THREAD

**Issue by core-code** [sedwards2009/extraterm#208]
the version numbers of the  'extraterm' 0.44.0 release are incorrect and still claim it is the 0.43.0 release. 

just select extraterm 0.44.0 in the Finder and hit GetInfo/QuickLook/ColumnView:

<img width="451" alt="Screenshot 2019-08-27 at 19 06 48" src="https://user-images.githubusercontent.com/1261954/63796197-ea092c80-c905-11e9-9782-82150685fc94.png">

**Comment by sedwards2009** [comment]
Thanks. This was reported yesterday in issue #207. It will be fixed in the next release.

**Comment by core-code** [comment]
thanks and sorry for the duplicate
