### ISSUE TITLE
Shortcuts conflict with emulation keys, breaks Emacs

### ISSUE THREAD

**Issue by sedwards2009** [sedwards2009/extraterm#21]
Extraterm is eating or has conflicting shortcuts for keys which are needed to run Emacs:

* meta (alt) prefix key doesn't work. this is a killer.
* some control keys don't work:
* ctrl-@ (set mark) -- no effect
* ctrl-space (set mark) -- not sure what this did, but everything stopped. a second ctrl-space made it work again.
* ctrl-^ -- no effect
* ctrl-\ (set input method) -- no effect

**Comment by leighklotz** [comment]
Itwouldbeniceif when you're in a box that's running emacs, extraterm automagically captures fewer keystrokes.

**Comment by sedwards2009** [comment]
Fixed in v0.11.0.
