### ISSUE TITLE
How to reinstall VS Code's "code" command back into Extraterm?

### ISSUE THREAD

**Issue by do-kevin** [sedwards2009/extraterm#210]
Hi there,

First off, I am using WSL for Extraterm. I don't remember what I did that caused this; however, I can no longer use  the command `code` inside Extraterm. Is there something I need to run inside Extraterm to get it use `code` and/or `code.cmd` from `Program Files/Microsoft VS Code/bin`?

I've tried looking inside my VS Code for the "install code in path command", but it doesn't show up unfortunately.

Edit: I also want to add that my Extraterm freezes much less now thanks to the memory leak fixes in the 0.44.1 release. When it does rarely freezes, I have to restart my computer.

**Comment by sedwards2009** [comment]
First try the normal Powershell or `cmd.exe` and see if the problem is present there. I do use VSCode on Windows and I would not be surprised if the `code.exe` simply isn't on the path. This isn't likely to be related to Extraterm though.

Happy to hear that the memory fixes are working out.

**Comment by do-kevin** [comment]
> First try the normal Powershell or `cmd.exe` and see if the problem is present there. I do use VSCode on Windows and I would not be surprised if the `code.exe` simply isn't on the path. This isn't likely to be related to Extraterm though.

![Untitled](https://user-images.githubusercontent.com/40156784/64735401-53a83f80-d49d-11e9-8577-1417c15286f1.png)

Sorry for posting an irrelevant issue :sweat_smile: 
`code` works on my Powershell and CMD; however, the command is not recognized when I switch to bash or zsh. Do you have an idea of what I should check next?

Also, how do you install custom fonts into Extraterm? I'm trying to get Powerlevel9k theme working.

**Comment by sedwards2009** [comment]
If you are using WSL then you will probably have different path in that environment. `echo $PATH` can tell you what your path is.

For the font, install it into your system and then next time you start up Extraterm you should be able to select it. In the future I want an easier way to do this.
