### ISSUE TITLE
Context menus in split-pane mode not displaying properly

### ISSUE THREAD

**Issue by krzysztof-callstats** [sedwards2009/extraterm#220]
Context menu for `Insert Field` and `Insert Title` buttons when in split-pane mode is out of the screen.

<img width="1440" alt="Screenshot 2019-09-23 at 17 20 01" src="https://user-images.githubusercontent.com/45563326/65438870-813ea280-de26-11e9-8ce9-15ee5525bd6d.png">

<img width="825" alt="Screenshot 2019-09-23 at 17 15 05" src="https://user-images.githubusercontent.com/45563326/65438925-99aebd00-de26-11e9-8ee8-e4b48a0a3deb.png">

macOS Mojave 10.14.6
Extraterm 0.44.1

**Comment by sedwards2009** [comment]
Fixed in 0.49.2.
