### ISSUE TITLE
[Feature Request] Improved Copy-Paste options

### ISSUE THREAD

**Issue by MartinSGill** [sedwards2009/extraterm#221]
A fairly common setup (and one I personally use daily) is to have copy-on-select and paste with a right click.

This might not be the easiest thing to do, given the context menu is already on right-click, but it's the first thing I missed when I started trying out extraterm.

**Comment by Kynolin** [comment]
If this feature is considered, please also keep the option to use middle mouse paste. It's a bit opposite for me, but middle mouse paste is what initially drew me to Extraterm compared to other new terminals.

**Comment by sedwards2009** [comment]
If I support "paste on right" it will be configurable and not the default. I'm kind of wondering what to do about the context menu if right mouse is set to paste.

**Comment by MartinSGill** [comment]
I generally have it set to ctrl-right-click for the menu.

I also usually have copy-on-select enabled so that ctrl+c can be freed up for it's more traditional interrupt role.

**Comment by ecometer** [comment]
It would be great to be able to configure the paste with a right click,
thanks
paolo

**Comment by sedwards2009** [comment]
Released in version 0.55.0.
