### ISSUE TITLE
Rightmost tab invisible when tab count exceeds window width

### ISSUE THREAD

**Issue by ceyhunkerti** [sedwards2009/extraterm#224]
if you open many tabs, the last tab(rightmost) is invisible when active.

![image](https://user-images.githubusercontent.com/6328046/67023050-d78fc000-f10a-11e9-8f11-9ed4a76e9c7c.png)

Also window actions and settings button disappears.

**Comment by sedwards2009** [comment]
I was aware of this. Thanks for making an issue for it.

**Comment by sedwards2009** [comment]
Fixed in 0.49.2.
