### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by rsliotta** [sedwards2009/extraterm#227]
Love this tool so far on my Chromebook with Crostini.  I was wondering if this is a way to disable the splash screen to speed it up.

**Comment by sedwards2009** [comment]
It is not possible to disable the splash screen. Removing the logo won't make it go faster. It would just mean that you're staring at a blank window for the same amount of time wondering if anything was happening.

Glad you like it though.

**Comment by rsliotta** [comment]
Simon,

Thanks for you entertaining answer!

Best Regards,


[signature_924272346]
[signature_903641230]

BOB LIOTTA
SVP IT ENTERPRISE ARCHITECT
robert.liotta@cevalogistics.com<mailto:robert.liotta@cevalogistics.com>
Tel : +1 904 928 2322
8800 Baymeadows Way West – Jacksonville FL 32256
www.cevalogistics.com<http://www.cevalogistics.com>
