### ISSUE TITLE
Help Installing (linux)

### ISSUE THREAD

**Issue by SirFireball3521** [sedwards2009/extraterm#228]
I'm sorry if this has already been answered or if I'm just being stupid.

When I followed the installation instructions in the user guide (I assumed "click on" means to run) and ran the ``extraterm`` file, it gave me the following error:
```
[7706:1114/1836.50.106937:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/sirfireballDownloads/extraterm-0.46.0-linux-x64/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```
I tried again after moving it all to ``root`` (which is not "somewhere convenient") and it did not output this error. It did not do anything.
I looked for any "setup" or "installer" scripts to run, but could not find any. What did I do wrong?

**Comment by sedwards2009** [comment]
There aren't any other special instructions which you should need to do.

What Linux distribution/version are you using?

**Comment by SirFireball3521** [comment]
Debian 10 64 bit. Newest version from github.

**Comment by sedwards2009** [comment]
This appears to be an instance of https://github.com/electron/electron/issues/17972

**Comment by sedwards2009** [comment]
A work around which is worth trying would be to unpack the extraterm zip like normal, and then go into that directory and run:

    sudo chown root chrome-sandbox
    sudo chmod 4755 chrome-sandbox

and then run Extraterm like normal.

The short story is that Electron which Extraterm runs on top of, uses an Linux operating system feature to improve security (by sandboxing), but Debian 10 doesn't have it available for normal uses by default. The fall-back solution involves a special wrapper executable, but it needs special root permissions which are not set by default if you just download the zip and use it.

A Debian package for Extraterm could set things up correctly though, but not aware of there being one. Either way a better solution needs to come from the Extraterm side for this.

**Comment by laxitg** [comment]
Unfortunately, for Extraterm v0.49.3 It still seems to be an issue on debian 10 (buster) with deb files also.

**Comment by sedwards2009** [comment]
@laxitg  Thanks for bringing this issue up again.

I've tried to fix it in the .deb but I don't have a hardened Debian around to test it on. In about 12 hours from now a nightly build will appear which contains a fixed .deb. Can someone try out this new deb and report whether it is now working for them. Nightlies can be found here: https://storage.googleapis.com/extraterm_builds/index.html

**Comment by SirFireball3521** [comment]
I can test this tomorrow.

**Comment by SirFireball3521** [comment]
The 2020-05-16 build seems to work fine, thanks!

**Comment by sedwards2009** [comment]
@SirFireball3521  thanks for confirming this fix!
