### ISSUE TITLE
Linux Crash

### ISSUE THREAD

**Issue by aidanharris** [sedwards2009/extraterm#23]
As far as I know this isn't an issue with extraterm but I'm posting this anyway since it might help someone else. Upon launching extraterm it crashed because of a limit on the number of inotify watches.

Doing the following made the error go away which allowed extraterm to launch:

## TypeError: Unable to watch path

If you get following error with a big traceback right after Atom starts:

  `TypeError: Unable to watch path`

you have to increase number of watched files by inotify. For testing if this is the reason for this error you can issue

 ` sudo sysctl fs.inotify.max_user_watches=32768`

and restart Atom. If Atom now works fine, you can make this setting permanent:

  `echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`

See also [#2082](https://github.com/atom/atom/issues/2082).

Source: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path

**Comment by sedwards2009** [comment]
Thanks for the info. Extraterm uses inotify watches to monitor its theme files to do live updates which is very handy if you're working on a theme. It is not vital to the function of Extraterm for 95%+ of users. It should thus handle this error condition and not blow up. Or I could make it an option somewhere for those who need live theme loading. It is a bug in other words.

**Comment by sedwards2009** [comment]
I've removed the code which watched the file system. This problem can't happen now.
