### ISSUE TITLE
[Feature Request] Tab names in session config

### ISSUE THREAD

**Issue by journeym** [sedwards2009/extraterm#231]
It was partially mentioned in https://github.com/sedwards2009/extraterm/issues/157
Please make it possible to configure the tab name in session types.
From my practice, i use separate session tabs configured for managing exchange / powercli / just powershell, and they all look alike after opening, sure i can rename, but that works only till application restart.

**Comment by sedwards2009** [comment]
This hasn't been forgotten. I want to get the extension system (more) up and running and then doing this as an extension.

**Comment by sedwards2009** [comment]
Fixed in v0.54.0.
