### ISSUE TITLE
Backspace disrupts the display of long command lines when extraterm-commands is enabled

### ISSUE THREAD

**Issue by laurent-indermuehle** [sedwards2009/extraterm#232]
Hi,
I love this terminal! It's by far the most feature rich, superb and the drag and drop of the tab to pane is a must have!

I often use command longer than a screen width. Everytime I use the backspace key the display is messed up. Sometimes the cursor goes the line above the command I'm on, sometimes it display text that is not what it executes when I press enter. I could even edit the prompt header.

I'm on Fedora 31, extraterm 0.48.0, zsh 5.7.1, oh-my-zsh 534ec60.
I tested with bash, it is the same.

When extraterm-commands 0.48.0 is disabled, I can edit long command line without any issue.

**Comment by sedwards2009** [comment]
I'm having trouble reproducing the problem here. Have you got a screenshot of it or maybe more details about how your prompt is set up, or some other condition that may be required to trigger it.

**Comment by Honiix** [comment]
Sure,
First I paste a long line:
https://imgur.com/ehrX2fc

If I add something at the end, no problem. I can even erase with backspace and delete.
https://imgur.com/lrj8MG1

But, If I move the cursor back (With left arrow, CTRL+left arrow, it doesnt matter), and I start editing, there the problem starts. First the characters changes places during my typing. And if I try to correct with backspace or delete it's even worse. Sometimes the cursor jump somewhere else, like here it decided to go a line above:
https://imgur.com/3ZBRw9G

**Comment by sedwards2009** [comment]
I think I've seen this problem ages ago on zsh and oh-my-zsh. The extraterm shell integration hooks into the command prompt to output special terminal sequences. Somewhere in oh-my-zsh it tries to guess the size of the prompt by analysing it, but it doesn't understand any of the extra terminal sequences and therefore just gets the size wrong. This causes the layout of the zsh prompt to become corrupt.

There is probably an oh-my-zsh friendly way of doing this, but I so far haven't dived into the oh-my-zsh code yet.

**Comment by sedwards2009** [comment]
@laurent-indermuehle  The latest Extraterm release contained a fix for zsh and the terminal integration. Please try it out.

**Comment by laurent-indermuehle** [comment]
Wonderful, the problem is resolved! thanks for the follow-up @sedwards2009
