### ISSUE TITLE
Getting Locale error message when sshing to Linux hosts

### ISSUE THREAD

**Issue by chris1984** [sedwards2009/extraterm#233]
Trying to connect to Red Hat Enterprise Linux 7.x hosts I am getting the following:

```shell
You are attempting to use a locale that is not installed.
```
The WSL I am using is Ubuntu 18.04.

Is there a way to set Locale in the settings (didnt see one)

**Comment by sedwards2009** [comment]
This hasn't got much to do with Extraterm itself. What is happening is that `ssh` is passing a whole bunch of environment variables on to the remote (red hat) host. By default a lot of variables related to locale are passed through. (Many which start with `LC_*`). One of those is the locale and it looks like that variable is set in WSL but is not supported on your Red Hat host.

I don't know right off the top of head which variable it is, but you'll have to figure that out and then either change it to something valid before using `ssh`, or maybe there is some option or flag for `ssh` to let you override it.

**Comment by chris1984** [comment]
Thanks for the pointer! I will take what you have given me and look a bit deeper. I will close this out since it is not related to Extraterm but to the env vars.
