### ISSUE TITLE
Frame label/controls not visible with very long command

### ISSUE THREAD

**Issue by ashb** [sedwards2009/extraterm#239]
A very long command (`BACKEND=postgres pytest --tb=short tests/api/common/experimental/test_trigger_dag.py::TestTriggerDag tests/jobs/test_backfill_job.py::TestBackfillJob::test_trigger_controller_dag tests/jobs/test_scheduler_job.py::TestSchedulerJob::test_scheduler_verify_pool_full -x` in this case) means the label/number and controls for a frame aren't visible. 

Version 0.48.0

![image](https://user-images.githubusercontent.com/34150/72479833-70f36e80-37ed-11ea-99b0-2646e5e7099e.png)

**Comment by sedwards2009** [comment]
Fixed in 0.49.2.
