### ISSUE TITLE
ctrl-6 not passed to vim/terminal

### ISSUE THREAD

**Issue by ashb** [sedwards2009/extraterm#240]
Ctrl+6 (or actually _any_ Ctrl+number key) are not passed through to vim, or a normal terminal.

**Comment by ashb** [comment]
Guessing the problem is here:

https://github.com/sedwards2009/extraterm/blob/966ddb6da06a0faa425677259e828b5b298323bb/extraterm/src/render_process/emulator/Term.ts#L2199-L2206

It's only handling Ctrl A-Z, not not other keys on the keyboard. Ctrl-6 sends \x1e in other terminals (INFORMATION SEPARATOR TWO)

**Comment by ashb** [comment]
The behaviour of other terminals seems to be to pass Ctrl+anything as anything if it's not recognized, and these mappings:

ctrl+2: nul
ctrl+3-7: \x1b-\x1e
ctrl-8: \xf7

**Comment by sedwards2009** [comment]
Do you know which other terminals are sending keys for Ctrl+<number>? I had a quick look around here and it looks like the behaviour for these keys it very inconsistent between terminals.

**Comment by ashb** [comment]
For Ctrl+6 it's been sent for every terminal I can remember using: xfce-term, Terminal.app and iTerm2. (Ctrl+6 is the default vim key binding for switching between buffers.)

**Comment by ashb** [comment]
Oh and the linux console/text mode does the same.

**Comment by sedwards2009** [comment]
Fixed in 0.49.1.
