### ISSUE TITLE
Python error on startup is not explicit enough

### ISSUE THREAD

**Issue by pukafever** [sedwards2009/extraterm#244]
**Issue:**
I ran into an issue while trying to launch extraterm on Windows 10, saying that it could not find a suitable python version to use.

**Fix:**
Installing python 3 with cygwin.

**Improvements:**
The js error should be more explicit and python 3 may be listed as a requirement in `README.md`.

**Comment by niancan** [comment]
me to ....

**Comment by sedwards2009** [comment]
Extraterm no longer uses Python here.
