### ISSUE TITLE
Extraterm won't stay open after changing startup configs

### ISSUE THREAD

**Issue by j4hangir** [sedwards2009/extraterm#246]
I added some arguments to the startup underlying console, now extrametrm opens, loads everything, and immediately closes.

**Comment by j4hangir** [comment]
I resolved the issue by modifying the `extraterm.json` directly, but this certainly isn't intuitive. At least a mechanism should be put in-place to prevent this behavior after first start.

**Comment by sedwards2009** [comment]
I think the rule here should be that if a new session closes without the user entering any input, then the window should stay open. That would have given you a fighting chance to fix the problem in Extarterm itself.

**Comment by sedwards2009** [comment]
In the coming version 0.49.2, terminals will stay open once the shell process exits. This will allow you to see any error message and give you time to go to the settings.

**Comment by sedwards2009** [comment]
Just released in 0.49.2.
