### ISSUE TITLE
desktop shortcut problems

### ISSUE THREAD

**Issue by deathtrip** [sedwards2009/extraterm#252]
There are a couple of problems with the desktop shortcut that's in the repo.
1. `Icon=utilities-terminal` shows the Konsole icon on KDE, even though there are proper icons for extraterm in /usr/share. I suspect it could be the case for other DEs also.

2. `Exec=bash -c '"$(dirname "%k")/extraterm"'` fails to start for me, while simply "extraterm" works.
I use zsh as my default shell, so maybe that's the problem.

**Comment by sedwards2009** [comment]
You must be looking at a package that someone else has put together. I've just got zip files which don't touch `/usr/share`. You should contact the people responsible for that package.

I have seen that the `.desktop` file in the zip doesn't work very well in some situations. KDE seems to be less fussy, but Gnome has more trouble. The `Exec=..` hack probably needs to be removed in a proper package though.

For the next minor release 0.49.2, I'm also going to publish a `.deb` which should work on most Debian and Ubuntu systems.

**Comment by sedwards2009** [comment]
A Debian package with working `.desktop` file has been released in 0.49.2.
