### ISSUE TITLE
bug windows not start: screen with '+' not prompt

### ISSUE THREAD

**Issue by Paul75** [sedwards2009/extraterm#256]
Hello,

I download the 0.49.2 zip and when Open I see like the screen.

Why ?

![image](https://user-images.githubusercontent.com/457062/77650043-27509e00-6f6b-11ea-8faa-b4e9598da4f2.png)

Tanks

**Comment by sedwards2009** [comment]
Fixed in 0.49.3.

Sorry it took so long.
