### ISSUE TITLE
Error trying to launch WSL 

### ISSUE THREAD

**Issue by MostHated** [sedwards2009/extraterm#257]
I am getting the below error as of today when trying to launch Extraterm. It was fine last night and I don't know of anything on my PC that would have changed since then.

![](https://i.imgur.com/uL7IWbS.png)

**Comment by MostHated** [comment]
Nevermind, I was just an idiot. I already had the window opened and it was on the taskbar and I didn't realize it and was trying to open another.

**Comment by sedwards2009** [comment]
In the latest release, Extraterm has better behaviour in this situation and it should still start up.

**Comment by MostHated** [comment]
Ah, very good. Thank you much.
