### ISSUE TITLE
Changing interface theme causes UI error

### ISSUE THREAD

**Issue by ebayer** [sedwards2009/extraterm#258]
Changing interface theme under Settings -> Appearance -> Interface -> Theme to anything other than "Two Dark UI theme" causes the following error on console:

```
[mainweb #0] An SASS error occurred while processing gui-components/gui-tabwidget.scss
Undefined variable: "$ui-tab-height". (Directories: /home/ebayer/workspace/extraterm-0.49.2-linux-x64/resources/app/extraterm/resources/themes/atomic-light-ui, /home/ebayer/workspace/extraterm-0.49.2-linux-x64/resources/app/extraterm/resources/themes/default )
```

The theme seems working until closing the application window but application can not be started again. This is the appearance of unusable application window after restart:

![Screenshot_20200408_093814](https://user-images.githubusercontent.com/2903013/78752488-df734300-797c-11ea-9ac0-72e7c347baf6.png)

Error console shows the same undefined variable error on second start.

Seems like #83 maybe.

**Comment by sedwards2009** [comment]
Issue #256 appears to be the same thing.
