### ISSUE TITLE
Auto-completion based on buffer

### ISSUE THREAD

**Issue by j4hangir** [sedwards2009/extraterm#264]
Thanks for the ongoing impressive job, the terminal emulator is becoming better and better every day 👍 

The only thing I miss as I used to work on my Mac with `iTerm` is its smart auto-completion feature, one could press a key and a drop-down box would open with suggestions from the buffer, say the line above:

```zsh
>>>
>>> name=root
>>> echo $n<HOTKEY>
````
There, `name` would be one of the top suggestions (pre-selected, similar to autocompletion in Fish)

I think implementing this wouldn't be that difficult, given that the buffer is readily available and it'd be merely a matter of ordering the suggestions based on their _distance to the cursor_ + _LD (Levenshtein distance)_. On the plus side, it's exceedingly a useful feature, reducing the strain on fingers to move and copy paste things around.

**Comment by sedwards2009** [comment]
Released in v0.58.0.
