### ISSUE TITLE
'[ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed' error after update

### ISSUE THREAD

**Issue by MostHated** [sedwards2009/extraterm#268]
Hey there,
    I just updated to 0.51.0 and upon opening it up, I keep getting the following error.

![](https://i.imgur.com/ivuCy6o.png)

**Comment by sedwards2009** [comment]
Nothing comes to mind. I'm pretty sure that I didn't touch anything in that area recently.

Does WSL from a standard Windows console work?

Is Python3 present in that WSL environment?

**Comment by MostHated** [comment]
Yeah, it seems to be working fine when I open it up in Windows Terminal. It also has python3, which can be seen below.


![](https://i.imgur.com/pQvlr79.png)

**Comment by sedwards2009** [comment]
I just installed 0.51.0 on a Windows machine here with WSL. It works fine.

What you can try is opening up  cmd.exe, `cd` your way into the Extraterm installation directory (`c:\Program Files\Extraterm\`) and then running:

    wsl.exe pwd

This should output the location of this directory as mapped inside your WSL installation.

My only remaining advice is to reboot, run as little as possible, uninstall and then re-install Extraterm and try again.
