### ISSUE TITLE
support for multiple WSL clients

### ISSUE THREAD

**Issue by IsCoelacanth** [sedwards2009/extraterm#270]
For cases when there's two WSL shells installed, currently passing `-d Debian` or something similar to WSL doesn't shift to that shell

**Comment by sedwards2009** [comment]
I actually have this small feature in the code base now, but there are a couple of other unrelated bugs which need to be fixed before I can do a new release.

**Comment by sedwards2009** [comment]
Fixed in 0.52.0.
