### ISSUE TITLE
Ctrl-backspace modifier not sent correctly

### ISSUE THREAD

**Issue by danielhuang** [sedwards2009/extraterm#271]
Ctrl-backspace does not delete the whole word in the shell prompt.

Hyper: (pressing Ctrl-backspace, then Ctrl-D to exit)
![image](https://user-images.githubusercontent.com/24739403/87232750-73471780-c38f-11ea-881f-3b15ad2e1764.png)

Extraterm:
![image](https://user-images.githubusercontent.com/24739403/87232762-8823ab00-c38f-11ea-8ff7-159bd16d0228.png)

**Comment by sedwards2009** [comment]
There appears to be some variety here among the different emulators. VTE based emulators on Linux send `^H` on Ctrl+Backspace, and `^[^?` on Alt+Backspace. Xterm also sends `^H` on Ctrl+Backspace, and something which might be garbage.

**Comment by sedwards2009** [comment]
Fixed in 0.52.0.
