### ISSUE TITLE
Toggle Show/Hide Window Global Hotkey

### ISSUE THREAD

**Issue by jdstapleton** [sedwards2009/extraterm#277]
![image](https://user-images.githubusercontent.com/5853065/90635397-27418b00-e1f7-11ea-83f2-0f8111adc56c.png)
(Another feature request would be to able to copy the text from that dialog)

Uncaught Exception: ReferenceError: window is not defined (..../DoLater.js:54:9)

I have tried different hot keys combinations in case it was because of a conflict, all exhibit the same error.

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

And running the default Unity UI

**Comment by sedwards2009** [comment]
This was fixed in v0.53.0 (which I forgot to mention in the release notes).
