### ISSUE TITLE
Extraterm not opening on Fedora KDE 32 !!!

### ISSUE THREAD

**Issue by orangcrsh** [sedwards2009/extraterm#286]
Hey there, I hope you are doing well in those hard times on all planet.

I am running at home a minecraft server and well, i don't really like "Konsole" default console. I just discovered Extraterm, which is verry beautifull :) 

I looked arround, no tutorial on Google. I downloaded as well the Linux package on official Github, but then if I read the documentation, it say to run "extraterm" exacutable file, which I am doing, I also tried to run extraterm.desktop file, it's loading, but nothing is happening.

please help !

**Comment by orangcrsh** [comment]
Also here is a screenshot if I run the executable in the console: 

![image](https://user-images.githubusercontent.com/48868326/94995138-45c2d200-056a-11eb-94ba-d5673057f674.png)

**Comment by orangcrsh** [comment]
Up !

**Comment by sedwards2009** [comment]
The zip version works here, so I'm at a bit of a loss as to the real problem. Did you just use `unzip` from a terminal to unzip it?

**Comment by orangcrsh** [comment]
I did right click and extract.

**Comment by orangcrsh** [comment]
![image](https://user-images.githubusercontent.com/48868326/95461310-146c4c80-0944-11eb-9591-79c428bd27e6.png)

**Comment by sedwards2009** [comment]
I'm setting up Fedora is a virtual machine. Did you use the KDE archive app? (`ark`, if I remember correctly)

The `.desktop` file might not work from the zip.

**Comment by orangcrsh** [comment]
I did right click and extract... I don't know the software

**Comment by orangcrsh** [comment]
And I have extracted the .Desktop file and tried ALL other files one by one ... 20 times.. downloaded/redownloaded...

**Comment by orangcrsh** [comment]
When you click on .Desktop it ask do you want to OPEN on RUN I say RUN

**Comment by orangcrsh** [comment]
Nothing... And it's the only thing that doesn't work on my KDE

**Comment by sedwards2009** [comment]
I just reproduced the problem in my Fedora virtual machine using KDE and its Ark app, via the "Extract here" menu item in Dolphin.

Now I just have to figure out why it fails.

**Comment by orangcrsh** [comment]
> I just reproduced the problem in my Fedora virtual machine using KDE and its Ark app, via the "Extract here" menu item in Dolphin.
> 
> Now I just have to figure out why it fails.

I'm so happy you put energy in the problem ^^

**Comment by sedwards2009** [comment]
By the way, the work around for you is to download the linux.zip file, then in the terminal unzip it with `unzip extraterm-.....zip` instead of using "Extract here" from Dolphin.

The root problem is that some unzip apps correctly support symlinks, while others don't. I'm now trying to remove any symlinks from the zip file entirely.

**Comment by sedwards2009** [comment]
Fixed in 0.54.0. It should work now regardless of whether your unzip tool restores the symlinks or not.
