### ISSUE TITLE
How do I customize the tab title from Bash?

### ISSUE THREAD

**Issue by Autofire** [sedwards2009/extraterm#289]
Hi!

I'm having issues with my hands so I am trying to set up voice activation on my computer. I'm using something called Dragonfly to build my own set of voice commands.

I can configure it to enable grammars based on the title of the window. I'd like to set up Extraterm to change the title of the tab to include the word "vim" while I have vim open. I figure I can do this by having an alias for vim that would change an environment variable (or run any other command) while vim is running and then change it back when vim closes.

Thing is... I'm not really sure how to do this? I've tried configuring PS1 but it just makes the titles on the tab break.

I have the extraterm commands set up for Bash, if it helps. I'm on Windows 10, and I'm using it with Ubuntu running within WSL 1.

**Comment by sedwards2009** [comment]
In the next version you will be able to configure the tab title in the session tab. And you will be able insert the current command name into your tab title, plus other stuff if you like. It is a template. For this to work you will need to be using the shell integration though.

**Comment by Autofire** [comment]
Awesome, thank you!

For now, I can get by with a workaround or two, but this will definitely be convenient to have.
