### ISSUE TITLE
Ctrl + Shift + Space not working (solved: GNOME Settings issue)

### ISSUE THREAD

**Issue by aral** [sedwards2009/extraterm#293]
Opening this issue so that it’s documented somewhere in case anyone else has this issue:

Check that `Ctrl + Space` (note `Shift` doesn’t have to be included) is not being bound to some other app in GNOME Settings. (In my case, Text Expander had it.) (I guess GNOME being GNOME, that was enough for a different app to not get notified for `Ctrl + Shift + Space`

:man_shrugging:

**Comment by sedwards2009** [comment]
thanks.

I wouldn't expect Gnome to grab that combo globally. Lots of other apps want it too.
