### ISSUE TITLE
Odd render of box drawing glyph

### ISSUE THREAD

**Issue by aral** [sedwards2009/extraterm#296]
The `╰` box drawing character is not rendered correctly.

## How it should look (e.g., in GNOME terminal):

![Screenshot from 2020-10-16 14-07-45](https://user-images.githubusercontent.com/41798/96262009-1758e400-0fb9-11eb-8d7c-6884f3a6b1e9.png)

## How it actually looks (in Extraterm):

![Screenshot from 2020-10-16 14-03-11](https://user-images.githubusercontent.com/41798/96261431-5cc8e180-0fb8-11eb-9009-d39d6bfe9ca4.png)

## Excerpt of string to reproduce the error

```
   💾     ❨JSDB❩  ╰─ Loading table synchronously
```

__Note:__ does not appear to be a font-dependent issue; can reproduce with all the fonts I tried including powerline and non-powerline.

Also, if you type the character and select it, displays correctly in reverse. If you select it in the output of a command, you see that the curved area is being drawn but in a dark colour.

**Comment by sedwards2009** [comment]
Thanks for this very clear bug report.

The fix is in now.

**Comment by aral** [comment]
Thanks so much, Simon :)

**Comment by sedwards2009** [comment]
Fix released in 0.54.0
