### ISSUE TITLE
can extraterm be installed/upgraded by pkg-manager such as yum/dnf ?

### ISSUE THREAD

**Issue by MintYale** [sedwards2009/extraterm#308]
As the title describes.
Installing/Updating an app by a command line is much more faster than any other ways. I tried `sudo dnf install extraterm*` and `sudo yum install extraterm*` yet all returns `No match`. If you can support installing this wonderful app by command line, it would be so very great.

**Comment by sedwards2009** [comment]
I publish Extraterm packages for some common formats and also I publish .zip files which can be run with a little manual work. But Linux distro have a ton of different package formats and I don't have the time to support each one. In these cases I rely on other people to take the .zip files and then package them themselves for their own platform. Someone in the Arch Linux does this for Arch. On the Windows side someone puts Extraterm up on Chocolately, etc.

You're options are to either package it yourself, or kindly ask someone in the Linux packaging community to add Extraterm. Some user run package repositories will take requests.
