### ISSUE TITLE
55.1 broke panes

### ISSUE THREAD

**Issue by laurent-indermuehle** [sedwards2009/extraterm#309]
Thanks again for your hard work!

I have a problem with panes since the upgrade to 55.1 with and without extra-commands.

In a single pane everything looks fine: 
![one pane](https://i.imgur.com/jzMp0rV.png)

When creating a pane (horizontal or vertical, same issue) the UI crashes and become unusable, no keyboard keys registered, no command palette:
![two panes](https://imgur.com/YSDKep3.png)

**Comment by sedwards2009** [comment]
This is from bugs introduced by the recent memory related fixes in the last release. I think I've gotten to the bottom of the problem now but still need to do more testing. A fix should be in the next few days.

thanks for everyone's patience here.

**Comment by sedwards2009** [comment]
Fixed in 0.55.2.
