### ISSUE TITLE
Initial directory couldn't be found

### ISSUE THREAD

**Issue by journeym** [sedwards2009/extraterm#310]
I have this error for every session type, and directory stays the root of extraterm, though i have defined initial directory. I'm using latest release.
![image](https://user-images.githubusercontent.com/7759734/99855757-320e1200-2b90-11eb-933c-ee099036f51d.png)
![image](https://user-images.githubusercontent.com/7759734/99855808-4baf5980-2b90-11eb-92da-994f5b3b4ab9.png)

**Comment by journeym** [comment]
Windows 8.1, problem persists even after uninstall / reinstall and deleting AppData\Roaming\Extraterm

**Comment by sedwards2009** [comment]
Fixed in 0.56.0.
