### ISSUE TITLE
Windows 10 2004, application starts then closes

### ISSUE THREAD

**Issue by journeym** [sedwards2009/extraterm#316]
Tried reinstalling, deleting /Appdata/Roaming/extraterm, nothing helps

**Comment by hartescout** [comment]
I am having the same issue, tried the same mitigations. Hapens with Binary install and choco install.

**Comment by journeym** [comment]
For me, the problem was i didnt have wsl distibution installed, after i have installed ubunu distribution, and got wsl command functioning in command prompt (opening linux subsystem prompt) everything started working.
Seems extraterm defaults to wsl on windows these days, which is really strange, should be cmd imo.
