### ISSUE TITLE
When opening command palette extraterm doesn't autofocus on input of the pane menu

### ISSUE THREAD

**Issue by hfpmartins** [sedwards2009/extraterm#319]
When opening the command palette and choosing, for example, the option of vertical split, the pane menu is not autofocused. This means that you need to use your mouse or shortcut key in order to choose from the available options. This was not the case before. Tested on Kubuntu 20.04 and extraterm v0.57.0

**Comment by sedwards2009** [comment]
Fixed in v0.58.0.
