### ISSUE TITLE
When opening Nano, you can't see the Nano Title text or the Shortcuts Keys when the appearance is turned to Transparent.

### ISSUE THREAD

**Issue by ProcrastinatingEntrepreneur** [sedwards2009/extraterm#320]
Just as said in the title. Can't see the text in the Terminal for Nano at all, just grey boxes and no shortcut keys, nothing. 
![image](https://user-images.githubusercontent.com/62977610/104772357-ec596a00-5738-11eb-8efb-89a2df4d9a94.png)

**Comment by sedwards2009** [comment]
Which operating system is this? This kind of thing has been reported before but I haven't had a way of reproducing it.

**Comment by ProcrastinatingEntrepreneur** [comment]
I am using Windows 10 with WSL2

**Comment by sedwards2009** [comment]
Duplicate of #283.

**Comment by sedwards2009** [comment]
Fixed in v0.57.1
