### ISSUE TITLE
terminal image viewer issues

### ISSUE THREAD

**Issue by NgrNxk** [sedwards2009/extraterm#323]
Hi!

It's great that ExtraTerm supports 24bit colours! Wonderful! I really only need it for one thing: TerminalImageViewer (tiv). Now, it works in principle but there is an issue if the image displayed is nearing the terminal height. Then, in the top quarter of the image the blocks jump around somehow. As long as I limit the height to a two thirds of the screen, it works with 24bit. And 256 colours work always -- regardless of height.
I tried disabling all plugins in Extraterm to no avail.

Regards
Adam

**Comment by NgrNxk** [comment]
I just tried an image that is pretty wide: here the issue already occurs with half a screen of output. It seems it's the amount of "pixels" displayed...

**Comment by sedwards2009** [comment]
Fixed in v0.58.0.
