### ISSUE TITLE
Lacks Cyrillic support on Mac OS

### ISSUE THREAD

**Issue by vyrgozunqk** [sedwards2009/extraterm#326]
This is feature request for Cyrillic support on MacOS. It seems to be working fine on Linux. I do not have issues in other terminals like iTerm or the built-in "Terminal", so I do not think it's local issue.  
Typing anything in Cyrillic leads to the ASCII code of the character being inputted instead of the character itself.

**Comment by sandikata** [comment]
It could be caused by a environment locale.
I can confirm in my linux works without issues.

**Comment by sedwards2009** [comment]
This might be related to dead keys and other keyboard input features. The recent 0.71.0 release has much improved support for different kinds of "keyboard" or character input. Try and let me know if that helps.

**Comment by vyrgozunqk** [comment]
Seems to be fine in the latest version, indeed.
Thanks!
