### ISSUE TITLE
*** Initial directory 'null' couldn't be found. *** on Linux

### ISSUE THREAD

**Issue by caedmon-kitty** [sedwards2009/extraterm#327]
Appears to be the same as #310.
I am using 0.57.1
Occurs with both zsh and fish.
Initial directory is correctly set in extraterm.json
The window does open in the correct initial directory.

**Comment by sedwards2009** [comment]
Can you attach or paste the contents of `~/.config/extraterm/extraterm.json` here?

**Comment by caedmon-kitty** [comment]
Attached.

**Comment by caedmon-kitty** [comment]
Attached

[extraterm.json.gz](https://github.com/sedwards2009/extraterm/files/5992189/extraterm.json.gz)

**Comment by sedwards2009** [comment]
Thanks. I can reproduce the problem here.

**Comment by sedwards2009** [comment]
Dupe of #318

**Comment by sedwards2009** [comment]
Fixed in v0.58.0.
