### ISSUE TITLE
0.59: only cygwin default shell works

### ISSUE THREAD

**Issue by NgrNxk** [sedwards2009/extraterm#340]
For all other shells (CMD, powershell, pwsh), I get ![this error](https://user-images.githubusercontent.com/2931938/115518485-7fe68d80-a288-11eb-8869-17d3136f71be.png) when trying to type something.

It's working fine with 0.58.

**Comment by sedwards2009** [comment]
My best advice right now is it uninstall it, then install again and try again. I have a bad feeling that installing over the top on Windows keeps too much old stuff around.

**Comment by NgrNxk** [comment]
Yeah, tried that: uninstalled extraterm, move %APPDATA%\extraterm out of the way and installed 0.59.1. Still the same issue. Downgraded to 0.59: still same issue. Downgraded to 0.58: works.

**Comment by sedwards2009** [comment]
Cygwin isn't supported anymore in the new Qt based version.

Closing issue.
