### ISSUE TITLE
can't open two adjacent "cygwin default shell"

### ISSUE THREAD

**Issue by NgrNxk** [sedwards2009/extraterm#341]
This is a strange one: if I'm on an already open "cygwin default shell", opening a new one via the menu does not work. This does not happen for powershell or CMD: these just work as expected. Now, upon trying to open a "cygwin default shell" two or three times, the second other shell, say "powershell", leads to three new tabs: two empty ones and the third being a "cygwin default shell" instead of "powershell". Strange behaviour.
This happened for a few versions now, but 0.58 and 0.59 are affected on my machine.

**Comment by sedwards2009** [comment]
Cygwin isn't supported anymore in the new Qt based version.

Closing issue.
