### ISSUE TITLE
LANG environment variable not set on macOS

### ISSUE THREAD

**Issue by yoichi** [sedwards2009/extraterm#350]
Extraterm does not set the environment variable LANG based on system environment settings.
Other terminals (Terminal.app, iTerm2, Kitty) do it.
I think it is useful if Extraterm also have that feature.

![スクリーンショット 2021-07-22 12 33 26](https://user-images.githubusercontent.com/107537/126586702-7d89d7b9-b9f0-4e62-a958-db60f0282e84.png)

There is a workaround by setting LANG in the shell config file.

Other terminals' implementation:

iTerm2:
https://github.com/gnachman/iTerm2/blob/a1eba0bca523aecfaf04297aafd5b7b253a0f689/sources/PTYSession.m#L2273
Kitty:
https://github.com/kovidgoyal/kitty/blob/61f5d3972f0fbe6bb1cc2c4cd1940f528c56cc20/kitty/main.py#L202

**Comment by MiXaiLL76** [comment]
`export LANG=en_US.utf-8`

in bashrc
