### ISSUE TITLE
Shortcut for changing font size

### ISSUE THREAD

**Issue by snippins** [sedwards2009/extraterm#36]
I am trying extraterm and absolutely love its unique features. Thank you for public this awesome software!

However, I would love to have some shortcuts to zoom in/out (<Ctrl>+/-/0). I love splitting/unsplitting when I was using terminator and as a result I need change the font sizes very often. Also, if you consider implementing this, I suggest you use different font sizes for each tabs.

Thank you!

**Comment by sedwards2009** [comment]
I'm glad to hear you like the unique features. Unique features are what I'm trying to explore.

Font sizing is a feature I intend to have. There already is a setting for font size for the whole application, and per tab sizing as a shortcut is also a possibility.

Another possibility is sizing on a per *frame* basis. When I get around to scripting features I want to be able to make it possible to set the font size based on the command being executed. For example, if I start a big compile then I want that output to automatically be made a small font.

I am open to suggestions on this one.

**Comment by snippins** [comment]
@sedwards2009 Thanks for the prompt reply

Very nice idea you got there, zooming per frame basis would be so useful.
In my opinion, the priority should be:

- [ ] Add changing font size shortcuts for tabs
- [ ] Add changing font size shortcuts for frames, this should work even if the command haven't finished. 

About automatically set font sizes, it is cool but I am not sure how practical it is. Firstly, determining a good font size is hard (even for the users themselves) as the same user might change preferences overtime. Additionally, the keyboard shortcuts should make it fast and productive enough.

Thanks.

**Comment by sedwards2009** [comment]
It is now possible to change the size of the terminal/text font up and down on a per tab basis.

Ctrl-Plus, Ctrl-Minus and Ctrl-Equals are the shortcuts.
