### ISSUE TITLE
Mouse Middle Button Click = Paste?

### ISSUE THREAD

**Issue by gaia** [sedwards2009/extraterm#363]
I am not sure why, using the current version, with any shell, the middle click causes a paste, only on Extraterm, but not on any other app.

These are my paste related bindings:

![image](https://user-images.githubusercontent.com/87547/145634431-b1774411-93c0-4a86-8aca-a4364437570d.png)

I'd really like to disable this as I find the middle click extremely annoying, my mouse is too sensitive and I have it disabled elsewhere.

**Comment by sedwards2009** [comment]
Go to the Settings, then General Tab, then "Mouse Button Actions" part.

**Comment by gaia** [comment]
mouse settings are 
![image](https://user-images.githubusercontent.com/87547/145691788-5cb33983-4983-4b0c-863e-656dc5a4a97a.png)

but it still pastes.

**Comment by sedwards2009** [comment]
You're right.
