### ISSUE TITLE
Fira Code: Extraterm crashes when enabling font ligatures

### ISSUE THREAD

**Issue by NervousNullPtr** [sedwards2009/extraterm#364]
System: Arch GNU/Linux w/ Linux XanMod-5.15.10

When selecting Fira Code as font, extraterm crashes and does not start anymore, unless I delete the config folder for extraterm.
When disabling Font Ligatures though and then selecting Fira Code, it works. Until I enable ligatures again, because then extraterm crashes again.
I've looked in the logfile, but didn't find anything useful, but I can still provide it if you need it.

**Comment by sedwards2009** [comment]
Fixed in 0.71.1.
