### ISSUE TITLE
Can't run extraterm on imac running Catalina

### ISSUE THREAD

**Issue by lowks** [sedwards2009/extraterm#378]
When I try to run extraterm, it says it needs at least MacOS 11.0, the problem is on older hardware there is not upgrade path towards 11.0. Is there a solution ?

**Comment by sedwards2009** [comment]
If you are talking about "Extraterm" and not the "Extraterm Qt" version, then no, there isn't much I can do about it.

**Comment by lowks** [comment]
I meant `ExtratermQT`

**Comment by lowks** [comment]
![Screenshot 2022-06-19 at 10 59 28 AM](https://user-images.githubusercontent.com/517395/174464049-a809c90c-3285-4bb6-ad14-81ee4f05da0e.png)
Picture Paints a thousand words

**Comment by sedwards2009** [comment]
I just had a quite look into this. Extraterm does declare its minimum version as 10.15 deep within its `Info.plist` file. So something else is tripping up. I suspect it might be the launcher executable. Building all the parts on a macOS 10.15 machine might be a solution, but GitHub Actions is completely removing support for building on 10.15 in a couple weeks. Given that I can't test this myself, it being a small set of affected users, and that macOS 10.15 (or earlier) support is drying up everywhere, I can't fix this problem.
