### ISSUE TITLE
Feature suggestion: Open new tab in same directory as current tab

### ISSUE THREAD

**Issue by cranndarach** [sedwards2009/extraterm#38]
Hi, awesome project! This has quickly become my primary terminal.

I have a suggestion regarding opening new tabs, essentially mirroring a feature from at least Linux Mint's native terminal: It would be really cool if, when a new tab is opened, the new tab could start in the previous active tab's working directory.

More clearly:
- Currently, all tabs start in the home directory, regardless of the wd of the active tab prior to opening a new one.
- If I open extraterm and `cd code/myproject`, then do `Ctrl+Shift+T` (or `Ctrl+Shift+P` "New tab"), I'd love for the new tab to open with the pwd set to `~/code/myproject`

I hope I'm explaining it well enough.

Thanks again for your hard work!

**Comment by sedwards2009** [comment]
Yes, I know what you mean and think that I would also like to have that feature too. It might be possible to make this work across SSH too.

Also, can I ask you how you discovered this project? and features do you like the most? (I'm curious of course)

**Comment by cranndarach** [comment]
I think I found this project on awesome-electron, but I feel like I also saw it referenced somewhere else (can't remember where right now) that further encouraged me to look into it. 

I think my favorite feature is the cursor mode -- that just makes things so much more efficient. I also like that there are relatively high-contrast dark themes by default. I know that sounds like a little thing, but it's a pretty big accessibility deal; white/bright interfaces give me a headache, but dark ones that are too low-contrast are very hard to read.

**Comment by sedwards2009** [comment]
I use the dark theme with a Linux style dark console theme. I had to tweak some of the colours to be brighter and readable. (Blue text on black is often unreadable for example That blue colour is brighter than the theme I originally borrow it from.)

I'm glad you like the cursor mode!

**Comment by kamarol** [comment]
i'd love to see this feature as well. my workflow consists of opening new tabs within a directory and interacting with the files within, once the feature is there i'll feel much more at home 😄
 also thanks for making such a beautiful terminal emulator, and for free!

**Comment by nanobot248** [comment]
I would really love to see this feature too, as i almost always need my terminals opened in the same directory. I've implemented this in a fork of your project some time ago, see https://github.com/nanobot248/extraterm/commit/4b473511e450d7508e97241a7d7fbcf8f0be5c5a
Maybe it helps, although there are probably easier ways to implement this.

**Comment by aral** [comment]
@nanobot248 I’d also love to see this (not just for new tabs but, since I use the auto-tiling feature in Pop!_OS, also in new windows). Is there any chance you could implement your version as an extension?

**Comment by sedwards2009** [comment]
The extension API doesn't support this kind of thing at the moment.

Right now I'm working on what I think of as a "tapas" release. Lots of small features and little bug fixes served up before the next big piece of work. I'll be digging into this small feature shortly.

**Comment by sedwards2009** [comment]
This feature will be in the next release. It is done.

**Comment by sedwards2009** [comment]
Released in version 0.55.0.
