### ISSUE TITLE
all terminals stay dark when switching from external screen back to laptop screen.

### ISSUE THREAD

**Issue by reivaxy** [sedwards2009/extraterm#381]
All open tabs remain dark, only solution is to quit and launch again, losing all sessions.
Seen on a Lenovo laptop with Windows 10 Enterprise 21H2

**Comment by sedwards2009** [comment]
What do you mean by 'dark'? Is the window just blank with a solid background colour or something?

I use Extraterm on a windows machine and switch monitors a lot, but I haven't seen thing problem. Does your laptop have multiple GPUs by any chance?

**Comment by tsoek** [comment]
This has been happening to me as well on version 0.59.3 when putting laptop to sleep and moving between home and office. I use multiple GPUs.

![image](https://user-images.githubusercontent.com/3100107/187723009-eb186b67-c209-45d9-9462-0819b7b16803.png)


![image](https://user-images.githubusercontent.com/3100107/187722650-e7ff42ca-7bd8-4f32-a3b0-868362095238.png)

**Comment by reivaxy** [comment]
Sorry I was away for some time, 
I concur with @tsoek's comment, it's actually after putting laptop to sleep and moving between home and office that I have the issue.
![image](https://user-images.githubusercontent.com/3592991/195015330-24bdf8b1-76d4-4591-9123-045638e7ef8b.png)

The console shows an error message each time the terminal gets / loses the pointer focus, I'll try to capture it next time :(

**Comment by sedwards2009** [comment]
This problem only appears in the older Electron based Extraterm, not in the current Qt based one.

Closing
