### ISSUE TITLE
Copy Command

### ISSUE THREAD

**Issue by Dan-Essin** [sedwards2009/extraterm#385]
What is this? It's not mentioned in the docs. Choosing it from rt-click or command palette just terminates the app.  Does this serve some purpose that is not obvious to me?

Thank you

**Comment by sedwards2009** [comment]
Which command exactly do you mean?

"Copy" shouldn't exit (or crash!) the app. Does this still happen on the latest release? Also, which operating system are you using?

**Comment by dragid10** [comment]
This happens to me as well! 
Its happening on the latest release: 0.68.0
OS: Ubuntu 22.10

**Comment by sedwards2009** [comment]
The problem happened to me too when I tried it.

**Comment by sedwards2009** [comment]
No longer crashes now.
