### ISSUE TITLE
keybinding not working correctly

### ISSUE THREAD

**Issue by accountgit** [sedwards2009/extraterm#387]
I tried setting a keyboard binding to ctrl + pageup and ctrl + pagedown and any of the key bindings doesn't work, appears as "5~" and ";5~" and doesn't execute the action (focus tab left and focus tab right respectively).

Tested in kde and gnome in linux x11 and wayland.

**Comment by sedwards2009** [comment]
yep, I see the same thing.

**Comment by sedwards2009** [comment]
Fixed in 0.67.
