### ISSUE TITLE
ExtratermQt on Mac OS X: Backtick not working

### ISSUE THREAD

**Issue by apiening** [sedwards2009/extraterm#397]
I can't type the `backtick` character "\`" in `ExtratermQt` on `Mac OS 12.6`. If I press the key, nothing happens.
All other special characters I've tried are working, so it doesn't look like a general keyboard mapping issue to me.
Any Idea why this is or what it is caused by?

**Comment by sedwards2009** [comment]
Which keyboard layout are you using?

**Comment by apiening** [comment]
I'm using the layout `German` in Mac OS X.

**Comment by sedwards2009** [comment]
Fixed in the 0.71.0 release.
