### ISSUE TITLE
The portable mode does not work since v0.67.0

### ISSUE THREAD

**Issue by naderi** [sedwards2009/extraterm#398]
Hi Simon,

Thank you for your great work!
Unfortunately, the portable mode does not work since v0.67.0.
Putting the setting's path into application_paths.json no longer has any effect.
Is that no longer possible to have a portable version?

Kind regards,
Ali

**Comment by sedwards2009** [comment]
This fix will appear in the nightly build in about 24 hours time:  https://storage.googleapis.com/extraterm_builds/index.html
