### ISSUE TITLE
Alt GR symbols fails again on Windows ?

### ISSUE THREAD

**Issue by Adi3000** [sedwards2009/extraterm#408]
Hello,

I'm a new user of extraterm. I hope I didn't miss a configuration setting 
Extaterm version : 0.69 
Extaterm command : Bash 
Shell : Bash 
Terminal : WSL type
WSL Distrib ; Debian
Font : Consolas
Theme : Two Dark
Added KeyBinding : Ctrl+A, Ctrl+Tab, Ctrl+N

I can do any of AltGr symbols on my AZERTY keyboard. On native WSL command prompt, it works fine.
![image](https://user-images.githubusercontent.com/1077725/211299358-bdc8ab81-7d7a-499d-8385-8fe946a4163c.png)

Is that something to do with this commit : 
https://github.com/sedwards2009/extraterm/commit/65efe86d3e72bec9350acf2494ccd3d1df00007d#diff-1d34b4d5761c91aef458f0ce706927fa0a565bea7fa90f7439f2f9ca8190570fR2200
 (issue #136 )

**Comment by Adi3000** [comment]
For information, it re-works in 0.59.4

**Comment by sedwards2009** [comment]
The whole underlying platform has been changed since that commit.

I tried qwertz on Windows and it worked, but haven't tried any AltGr chars yet.

**Comment by Adi3000** [comment]
I just test under QWERTY, if I'm not wrong according to internet, `AltGr` is mainly substitution for `Ctrl+Alt`, `AltGr` on Qwerty is works weirdly, but `Ctrl+Alt` works fine.
On Qwerty, `[Ctrl]+[Alt] + [one of the top bar number]` works fine : it display symbols
On Azerty, None of `[Ctrl]+[Alt] + [one of the top bar number]` works : it display a blank character, or maybe an undisplayable character (terminal seems to crash as if I was displaying a binary file with one of the char mapped)

**Comment by sedwards2009** [comment]
Fixed in the 0.71.0 release.
