### ISSUE TITLE
Shortcuts should be editable

### ISSUE THREAD

**Issue by rapha8l** [sedwards2009/extraterm#41]
Hi,

Thanks for your work
Shortcuts should be editable (if they are, I didn't find a way to do it on debian)
Example :  Ctrl+a is set in keybindings to select all, though it's painful when you have the habit to use it to go at the beginning at the line, in term or in emacs

Thanks

**Comment by sedwards2009** [comment]
Now that you mention it, it might just be a good idea to offer readline/emacs/etc style bindings as a built in option too straight out of the box.

**Comment by rapha8l** [comment]
Thanks !

**Comment by nbelakovski** [comment]
Is there currently any way to edit the bindings? Surely they're stored in some sort of editable config file?

**Comment by nbelakovski** [comment]
Ah, found it, keybindings.json. Looks like it requires a restart of extraterm to pick up the changes, but I was able to change the tab switching to Ctrl-Tab and Ctrl-Shift-Tab successfully. Looking forward to using this thing more, especially happy about the WSL support!

**Comment by sedwards2009** [comment]
There is an issue to make the bindings fully configurable. #79 I just bumped up its prio since it appears to be a show-stopper for a lot of people.
