### ISSUE TITLE
Some altgr combination doesn't work on Ubuntu with azerty keyboard

### ISSUE THREAD

**Issue by johnraz** [sedwards2009/extraterm#411]
I have some issues typing the below characters with an azerty (belgian) keyboard on ubuntu 22.04
```
~ (altgr + =)
` (altgr + µ)
´ (altgr + ù)
```
Every other keyboard combination with altgr work properly

This might be related to https://github.com/sedwards2009/extraterm/issues/408 maybe?

**Comment by sedwards2009** [comment]
I'm using Linux Mint here and on the basic Belgian layout `altgr + = ` acts as an accent key which combines with the next letter if possible. i.e. I can write "français". But Extraterm doesn't handle it correctly but the other apps do. So, finally I can reproduce this keyboard problem. :tada:

**Comment by sedwards2009** [comment]
Fixed in the 0.71.0 release.
