### ISSUE TITLE
Custom keybindings only activate after opening settings

### ISSUE THREAD

**Issue by tecfu** [sedwards2009/extraterm#413]
- Expected Behavior: 
Custom keybindings applied and saved in a previous session should work at the start of a new session. 

- Observed Behavior: 
Some custom keybindings only work after opening the settings tab in a new session.

- Steps to Repeat: 
1. Install on Ubuntu 20.04 via direct download
2. Move to Home directory
3. Hamburger Menu > Settings > Keybindings > Terminal > Reset VT
4. Replace keybinding with `Alt+K` 
5. Restart Extraterm
6. echo hello
7. Press Alt+K
8. Observe nothing, open settings menu
9. Switch to previous tab
10. Press Alt+K
11. Observe the terminal reset as expected (keybinding worked)

---

Thanks for all your work on the project, I know maintaining something like this can be overwhelming. Hang in there.

**Comment by sedwards2009** [comment]
Thanks for the encouragement, and the detailed report.

I've seen a few times where keybindings don't work when they should and I haven't been able to reproduce the problem on demand. I hope your steps do the trick.

**Comment by sedwards2009** [comment]
I can reproduce the problem here. :ok_hand:

**Comment by sedwards2009** [comment]
Fixed in the 0.71.0 release.
