### ISSUE TITLE
Allow changing title on the tabs 

### ISSUE THREAD

**Issue by accountgit** [sedwards2009/extraterm#45]
On konsole when you login to a server over ssh the title is/can be changed to the name of the server.
Maybe will be possible if not that, allow changing from the cli the name of the tab before connecting or allow this kind of modifications as a command ouput handling rules.

Seems that 
echo -ne "\033]0;SOME TITLE HERE\007"
changes it, but it automatically returns to the current path.

**Comment by sedwards2009** [comment]
Extraterm  supports that code to set the window title. Other than that it doesn't touch the title. Most likely your shell and shell on the remote machine are setting the title when they print the shell prompt.

**Comment by accountgit** [comment]
.bashrc was setting it, sorry.

Thank you.
