### ISSUE TITLE
Incorrect rendering of unicode characters

### ISSUE THREAD

**Issue by sedwards2009** [sedwards2009/extraterm#46]
The demo here https://github.com/yaronn/blessed-contrib uses (and abuses) all sorts of unicode characters in its dashboard and charts. As we can see in this screenshot below, Extratrem doesn't correctly render it.

![terminal-dashboard](https://cloud.githubusercontent.com/assets/6926644/21944714/ef32da28-d9d7-11e6-8a22-3c3312f250ae.png)

The main problem seems to be the widths of the characters which are not monospace even though Im using a good monospace font. Extraterm should handle this better.

**Comment by ashb** [comment]
I'm having issues where some emoji characters are being clipped: U+2717/✗  for instance:

![image](https://user-images.githubusercontent.com/34150/72432922-1d9f0300-3790-11ea-808a-d49fb5089bcf.png)

Compare to the same thing in Konsole (same font, but maybe at different size):

![image](https://user-images.githubusercontent.com/34150/72433027-6951ac80-3790-11ea-923d-8839c88aab27.png)

I understand this is a tricky problem - is there anything I can tweak?
