### ISSUE TITLE
Alt modifier not send with back space

### ISSUE THREAD

**Issue by accountgit** [sedwards2009/extraterm#47]
Backspace with any modifier always is send as back space.

$ showkey -a
^?      127 0177 0x7f -> alone
^?      127 0177 0x7f -> with ctrl 
^?      127 0177 0x7f -> with Alt
^?      127 0177 0x7f -> with ctrl + alt

I have it bound to delete word in bash and only can make it work (one at a time) with Esc + backspace.
Esc + backspace, esc + backspace, esc +backspace,... works.
esc+backspace + backspace+backspace doesnt' work either.

**Comment by sedwards2009** [comment]
Which terminal emulator have you previously been using?

This is what I see on Konsole:

`
^?      127 0177 0x7f <- Backspace

^[^?     27 0033 0x1b <- Alt + Backspace
        127 0177 0x7f

^?      127 0177 0x7f <- Ctrl + Backspace

^[^?     27 0033 0x1b <- Ctrl + Alt + Backspace
        127 0177 0x7f
`

**Comment by accountgit** [comment]
Konsole, as you tested.

**Comment by sedwards2009** [comment]
It is now the same as Konsole and other Gnome VTE terminals with regards to the backspace key.

It will be in the next release, probably later today.
