### ISSUE TITLE
Extraterm freezes on linux x64

### ISSUE THREAD

**Issue by rapha8l** [sedwards2009/extraterm#48]
Hi,

The 0.19 worked well, though the 0.20 has some problems : it freezes on "preparing" and nothing more happens.
Launching it from another term does not give errors, though strace gives this : 
recvmsg(25, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
write(60, "\0", 1)                      = 1
recvmsg(25, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(25, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=25, events=POLLIN}, {fd=32, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(25, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(25, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=25, events=POLLIN}, {fd=32, events=POLLIN}], 4, 332) = 1 ([{fd=32, revents=POLLIN}])
recvmsg(25, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)

(I did not put the whole trace as it's huge and maybe not useful)
Seen on two different machines

Thanks

**Comment by sedwards2009** [comment]
That doesn't let me a lot, I'm afraid. What you can try is starting extraterm up from a different terminal and give the `--dev-tools` flag. (I think this is in the current release.) It should open up the UI and also the chrome dev tools window. In the console tab there you might be able see a real error message.

**Comment by rapha8l** [comment]
Thanks for your reply
Seems it's not in this release 

 extraterm --dev-tools   
  error: unknown option `--dev-tools'

**Comment by sedwards2009** [comment]
Bummer. To try to get it to start up you can delete or move the directory `~/.config/extraterm`. That is where all of the temp stuff and config is stored.

**Comment by rapha8l** [comment]
I also tried by removing this directory, without success

**Comment by sedwards2009** [comment]
I'm quickly running out of ideas. I'm happily running the 0.20 release on two Linux (Ubuntu 16.04 +Neon) machines and on Window+cygwin. I had a look in git and didn't see anything exciting between 0.19 and 0.20.

What are you using exactly? Does it also fail on a clean user account?

**Comment by rapha8l** [comment]
It's 2 debian boxes running testing, I'll try with another account

**Comment by sedwards2009** [comment]
If the problem shows up on a clean account then there is a good chance that I can reproduce the problem here.

**Comment by rapha8l** [comment]
Hi, I've just tried on a clean new account with the same result, ie extraterm launches and freezes on "preparing"

**Comment by rapha8l** [comment]
Hi,

I've just tried back 0.19, and I get the same problem, though it worked before, could be distribution related, but I don't know how

**Comment by sedwards2009** [comment]
I tried Debian Jesse last night and saw that the node-sass binary fails due to a std C++ lib blah balh incompatibility problem. I hope that is a matter of just recompiling it against an older lib.

**Comment by rapha8l** [comment]
I use the nodejs from the node project repository : 
nodejs            6.10.0-1nodes
Could it be a problem ?

**Comment by sedwards2009** [comment]
That won't be a problem. It doesn't use any local `node` binary to run.

**Comment by sedwards2009** [comment]
I can now confirm that building the node-sass binary on Debian stable results in something which runs on Debian stable and also still works on my Ubuntu 16.04.

I'll try to build it on an even older Linux distro like CentOS 6 (=as recommended by a coworker at my day job).

**Comment by rapha8l** [comment]
thanks !

**Comment by sedwards2009** [comment]
I've put up a v0.20.1 just for Linux x64. Please try it out.

**Comment by rapha8l** [comment]
Thanks a lot
Unfortunately, it's the same, though I'm not on debian jessie but on testing (soon stretch)

**Comment by sedwards2009** [comment]
ok, then I'll just have to install Debian testing here and see what happens. thanks

**Comment by rapha8l** [comment]
Thanks, I'll brought you way too much work :)

**Comment by sedwards2009** [comment]
With some difficulty I've now managed to get Stretch working inside Virtual Box, and I have to report that Extraterm starts up fine under Gnome.

Is there anything about your set up which may be different or relevant?

**Comment by rapha8l** [comment]
I'm using i3, and previously awesome, and it was working well, maybe I installed something that broke

**Comment by sedwards2009** [comment]
Does Chromium start up on your machine?

**Comment by rapha8l** [comment]
yes, but another browser based on chromium (brave) does not start saying : 
FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

**Comment by sedwards2009** [comment]
That is a very interesting finding. It sounds like the same thing.

I found this issue at Brave: https://github.com/brave/browser-laptop/issues/6902

Their advice is do: https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel#1122977

**Comment by rapha8l** [comment]
Thanks, indeed it works for brave but not for extraterm

**Comment by sedwards2009** [comment]
I'm running out of idea here. I quickly tried it under i3 and it still worked.

Can you do a `dpkg-query -l` and put the output here or somewhere I can get it? It will list all of the installed packages and versions. Maybe there is something to learn from that.

**Comment by rapha8l** [comment]
Thanks 
http://pastebin.com/ZzpdvheH
Anyway, I can live without :) don't bother too much !

**Comment by sedwards2009** [comment]
I'm not seeing anything really exciting here either. Once the next release is out you try the `--dev-tools` flag.

**Comment by rapha8l** [comment]
ok thanks

**Comment by sedwards2009** [comment]
This issue is now over a year old. If the problem is still present in the latest release then create a new issue.
