### ISSUE TITLE
Logo for Extraterm

### ISSUE THREAD

**Issue by sedwards2009** [sedwards2009/extraterm#50]
This issue tracks the logo request over at https://github.com/g-harel/open-source-logos/issues/4

**Comment by SolarAquarion** [comment]
It's all about the icons really.

**Comment by sedwards2009** [comment]
Yes, it's crazy just how important logos for software projects have become in the last 5-10 years.

There is some work on a logo, although @g-harel seems to be experiencing an episode of the "just too busy to doing other stuff", I'm guessing. That is just the way things go.

**Comment by g-harel** [comment]
Yeah sorry about that, I'll get on it

**Comment by sedwards2009** [comment]
The logo work is all done now and integrated into Extraterm.

**Comment by g-harel** [comment]
: tada:
