### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by ChicK00o** [sedwards2009/extraterm#51]
For details, its a Babun installation with python3 installed.
Windows 10 home edition

On launch
![extratermerror](https://user-images.githubusercontent.com/5801907/27832062-e12d2d08-60ea-11e7-90af-3f0fa7cd8d40.PNG)

After i press okay the terminal does load, but no prompt is enabled
![extratermerror2](https://user-images.githubusercontent.com/5801907/27832126-1e9330c0-60eb-11e7-9544-be0fe96d2b62.PNG)

**Comment by sedwards2009** [comment]
Have you oly got python3 installed? no python2?

**Comment by ChicK00o** [comment]
well its a fresh installation of Babun and i had only installed python3 as the FAQ mentioned. But I just installed Python2 too, but the error still remains the same.

**Comment by sedwards2009** [comment]
I've been able to reproduce the problem on a Windows 10 machine here.

**Comment by sedwards2009** [comment]
I just saw that on my freshly installed babun that the `python3` command in the normal babun shell/terminal does absolutely nothing. It looks like babun's python3 is broken.

**Comment by sedwards2009** [comment]
Babun's out-of-the-box cygwin installation is broken. The way to fix it is to first quit any babun shells/terminals, and then from the windows explorer go to the babun installation directory (e.g. `c:\users\simon\.babun\`), and then run the `update.bat` script. This will update all of the cygwin parts. Afterwards, extraterm should start up and run correctly.

**Comment by ChicK00o** [comment]
Yes that worked thanks a lot!!!
