### ISSUE TITLE
extraterm commands in babun 

### ISSUE THREAD

**Issue by ChicK00o** [sedwards2009/extraterm#52]
well after your help with getting extraterm to work on babun, i have been for the life of me trying to integrate the "setup_extraterm_zsh.zsh" with it. I put all the files in the root home folder i.e C:\Users\[UserName]\ and added the "source setup_extraterm_zsh.zsh" at the top of the .zshrc file. When i start extraterm i see the echo "Setting up Extraterm support." printed on the console. the first time press "ls" i get the bar mentioning the command. but the second time i do it, there is no bar created. its as if it stops working.

**Comment by sedwards2009** [comment]
Just comment out that `source setup_extraterm_zsh.zsh` in your `.zshrc` for now.

Does it work if you open up Extraterm, go to the directory holding `setup_extraterm_zsh.zsh`, and run `source setup_extraterm_zsh.zsh`. Does running `ls` a few times produce frames around it?

(May be it is better to place `source setup_extraterm_zsh.zsh` at the end of `.zshrc`.)

**Comment by ChicK00o** [comment]
Yup at the end of the file!! Thanks sed, sorry for the trouble

**Comment by sedwards2009** [comment]
That's fine. You're giving some good feedback, and I've been improving the documentation because of it. Most people would just hit the same obstacles and silently give up.
