### ISSUE TITLE
Alignment and "X close"

### ISSUE THREAD

**Issue by ChicK00o** [sedwards2009/extraterm#53]
![rightaignment](https://user-images.githubusercontent.com/5801907/27993376-82eda11a-64c7-11e7-8d9b-782e2524e5d7.PNG)

As you can see, for the theme "babun" the right alignment of data is haywire, also when using tab autocomplete, the command moves to the center of the screen, and a shadow of the typed command remains, could be a theme issue not sure yet.

Closing tabs in fine, but if you close Extraterm using the windows "X button", java exceptions are thrown.
![excep](https://user-images.githubusercontent.com/5801907/27993405-1ea9bb02-64c8-11e7-8a11-3774b759c4c8.PNG)
![excep2](https://user-images.githubusercontent.com/5801907/27993406-1eab1402-64c8-11e7-8b08-e789bdcaff47.PNG)

None of these are blocking or high priority

**Comment by ChicK00o** [comment]
the alignment and auto completion problem exist with other themes too

**Comment by sedwards2009** [comment]
Are we talking about the alignment of the `/usr/local` in the shell prompt?

**Comment by ChicK00o** [comment]
yes alignment of "/usr/local" as well as the auto suggestion commands "rm node-v8.1.3" got auto completed in the middle of the screen as "rm node-v8.1.3.tar.gz", it should have just got overridden not added ahead in line

**Comment by sedwards2009** [comment]
I can reproduce both problems here too.

**Comment by sedwards2009** [comment]
The crash on window close problem is fixed on github and will be in the next release.

**Comment by sedwards2009** [comment]
This last commit here fixes the problem almost completely. It is still misaligned but only by the width of the last command status code. (i.e. code 0 is 1 char width, code 127 is 3 chars wide.)
