### ISSUE TITLE
I packaged extraterm for arch

### ISSUE THREAD

**Issue by SolarAquarion** [sedwards2009/extraterm#54]
It just need a desktop file and icons

**Comment by sedwards2009** [comment]
I can add a .desktop file for the next release which should be within the next week.

**Comment by SolarAquarion** [comment]
Sound's good

**Comment by sedwards2009** [comment]
I just released 0.26. There is a .desktop file on on github. The icons can be found in `src/logo/`. There should be a 256x256 version which you can scale to produce which every sizes Linux desktops require these days.
