### ISSUE TITLE
The "lines" are cut in half

### ISSUE THREAD

**Issue by SolarAquarion** [sedwards2009/extraterm#55]
I only see "half" of the command line, and not the whole, unless i press enter

**Comment by SolarAquarion** [comment]
It's fixed when i press "tab" but it's a oddity

**Comment by sedwards2009** [comment]
Have you got a screenshot? I  know of one case where the line positioning can be screwed and it is related to characters in the font being too tall or too wide. (Yes, even though every character should be the same size in a monospace font!)

**Comment by SolarAquarion** [comment]
https://i.imgur.com/X1IUzua.png

**Comment by sedwards2009** [comment]
Which font are you using exactly?

**Comment by SolarAquarion** [comment]
@sedwards2009 Fantasque Sans Mono.
![screenshot from 2017-07-24 23-38-20](https://user-images.githubusercontent.com/5307016/28554739-373a011a-70c9-11e7-9a3a-a02cb62df4c2.png)

**Comment by sedwards2009** [comment]
I think what is going on is that you're using a funky powerline style prompt which uses characters which are not in Fantasque Sans Mono but come from the powerline fall back font. These characters have different sizes compared to your normal font. This screws up the line height calculations by making some lines taller than expected.

I had a look into this problem recently but the couldn't come up with a quick (and good) solution at the time.

**Comment by sedwards2009** [comment]
@SolarAquarion I'm trying to reproduce this problem, but not having much luck. How did you get the house icon and tick symbol into the prompt? Which font is that?

The problem is most likely some of the glyphs in the rows being taller or wider than the normal monospace characters. I just need to find out what the fonts are being used for the extra symbols.

**Comment by SolarAquarion** [comment]
CodeNewRoman NF

**Comment by sedwards2009** [comment]
@SolarAquarion Can you tell me if this is still a problem in recent releases? There was at least one fix put in for this kind of problem.

**Comment by sedwards2009** [comment]
@SolarAquarion  :point_up:

**Comment by sedwards2009** [comment]
I'm just going to close this issue due to inactivity. A lot of changes have been made in this area since this issue. If it is still a problem then someone can make a new issue.
