### ISSUE TITLE
Ctrl-Shift-Space does nothing

### ISSUE THREAD

**Issue by eater** [sedwards2009/extraterm#58]
I'm running Extraterm on xfce, and nothing else is grabbing the keypress as far as I can tell. 

And there doesn't seem to be a way to change keybindings so I can toggle Cursor Mode another way.

**Comment by sedwards2009** [comment]
Can you get into Cursor mode via the command palette? (You should see a blinking vertical cursor.)

Is there anything else about your system that might be important? (keyboard settings? Language settings?)

**Comment by eater** [comment]
Aha, I ran `xev` and figured out that a script was silently stealing Shift-Space. Still would be great to have customizable bindings.

**Comment by sedwards2009** [comment]
Good detective work.

Customisable bindings are on the big long TODO list.
