### ISSUE TITLE
I love this project!

### ISSUE THREAD

**Issue by philer** [sedwards2009/extraterm#6]
There's a [rant on reddit](https://www.reddit.com/r/linux/comments/4asx9g/is_there_a_terminal_that_doesnt_make_me_feel_like/) about the outdated way terminals work. It's like nothing has changed in decades. Please keep it up, this is my shimmer of hope on the horizon.

Meanwhile in that rant you might also find a few ideas for additional features, if you are so inclined. ;)
I'm not sure if I can help myself. There seems to be some css and js around, so I'll go check that out.

**Comment by sedwards2009** [comment]
Thanks for the encouragement. If there are more ideas just enter them here on github. I need to fill up the issue tracker with all of the features I've been considering. The development page briefly describes a lot of them at the bottom: https://github.com/sedwards2009/extraterm/blob/master/docs/development.md

I want to get the CSS and theme stuff sorted out next. It is half implemented and when it is mostly done people can go to town with themes and stuff.

**Comment by philer** [comment]
I'd love that option of having a user editable CSS file (preferably via a preprocessor like LESS). Atom is doing a lot of great things in that direction.

**Comment by sedwards2009** [comment]
Extraterm is already using SASS (in the form of SCSS) to process the CSS files which are used to style each of the custom elements internally. This SASS work needs to be extended to all of the app, and then things like theming need to defined and implemented. A user editable CSS or SCSS file fits in that picture.
