### ISSUE TITLE
Opening a new tab requires mouse click to start typing

### ISSUE THREAD

**Issue by jigawot** [sedwards2009/extraterm#60]
When I set "Show Tips" to Daily or Never, new tabs won't let me start typing unless I click in the window.  If I alt-tab away and back it still doesn't work, so it appears it isn't just a focus issue.  It requires a mouse click in the active window or tab before I can start typing in the terminal.  When I set it back to "Show Tips: Everytime" I can open new tabs using the keyboard shortcut and start typing immediately.

I'm using Ubuntu 16.10.

**Comment by sedwards2009** [comment]
Thanks for reporting this. I was just able to reproduce the problem, so it should be fairly easy to fix.

**Comment by jigawot** [comment]
Glad to help.  Thanks for writing an awesome terminal emulator!

**Comment by sedwards2009** [comment]
Thanks.

Right now the roadmap for Extraterm is determined by my personal wishes and desires, but if you have a wishlist of your own or other feedback then you are free to put it in a new issue here.

**Comment by sedwards2009** [comment]
Fixed and released in 0.29.0.
