### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by richard-scott** [sedwards2009/extraterm#65]
I've just downloaded the latest [0.29.1](https://github.com/sedwards2009/extraterm/releases/download/v0.29.1/extraterm-0.29.1-win32-x64.zip) for Windows and unzipped the file. Double clicked the extraterm.exe and got this error on the first run.

![2017-10-06 09_28_15-error](https://user-images.githubusercontent.com/5149834/31269541-d080274e-aa78-11e7-8159-4676c7eb0d67.png)

On the 2nd run, I got this error which also looks to be due to the Roaming\extraterm folder not being created.

![2017-10-06 09_29_40-error](https://user-images.githubusercontent.com/5149834/31269582-f755c536-aa78-11e7-97a3-6b377ce8710d.png)

However, this time the AppData\Roaming\extraterm directory exists, but there is no extraterm.json file.

**Comment by sedwards2009** [comment]
Thanks for reporting this. The first problem you found appears to be easy to fix for me, but it is a show stopper for everyone else. I'll look into now and may have to produce a bug fix release for this.

The second problem is a known limitation at the moment. Install `python3` inside your cygwin installation and it should work.

**Comment by sedwards2009** [comment]
Fixed in v0.29.2 https://github.com/sedwards2009/extraterm/releases/tag/v0.29.2
