### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by justUmen** [sedwards2009/extraterm#66]
Is it possible to achieve full background transparency ? (See the OS desktop instead of colored background of the terminal)  
I already have a very simple custom css :  
`*{background:rgba(0,0,0,0) !important;}`  

But `--enable-transparent-visuals` is not recognized as a parameter by `extraterm`.

**Comment by sedwards2009** [comment]
The platform Extraterm is built on (Electron) doesn't support transparent windows very well at the moment, not without a bunch of limitations and bugs on the different operating systems. So, I'm hesitant to spend time on this issue at the moment, but I will keep it here in case the situation in Electron improves.

**Comment by jwhipp** [comment]
Just wanted to add to this, it's a requested feature of Hyper as well.  While they also don't support it put of the box, it can be added via a plugin which I'll link here.  I am wondering if something similar to what this plugin is doing for Hyper could be done here.

https://www.npmjs.com/package/hyper-opacity

**Comment by sedwards2009** [comment]
@jwhipp It looks like that plugin actually changes the opacity for the whole window, text included.

**Comment by jwhipp** [comment]
This is true, which I think on Windows is the standard method.   Personally I think it's fine depending on your theme.   Here's a screen shot of Hyper with it in action.

![image](https://user-images.githubusercontent.com/556332/51063099-bd8ee300-15b6-11e9-9a66-66697f460e27.png)

**Comment by ackstorm23** [comment]
It seems an essential feature of a good terminal to support transparency.  I can think of few successful terminals (beyond the default terminal of operating systems, which terminal enthusiasts rarely use) that don't have this feature.

**Comment by sedwards2009** [comment]
This was added for Window 10 in Extraterm 0.47.0.
