### ISSUE TITLE
extraterm.exe exits with "TypeError: Cannot read property 'cygwinDir' of null"

### ISSUE THREAD

**Issue by nathan-sain** [sedwards2009/extraterm#7]
I'm trying to use Extraterm v5.0 on Windows 7 with a Cygwin 64 install. Debug output also includes this warning "2016-03-17 16:46:41.562 DEBUG [main #0] Couldn't find user configuration file at
 C:\Users\UCA\AppData\Roaming\extraterm.json"

**Comment by sedwards2009** [comment]
It is having trouble finding your cygwin installation directory. It looks in the windows registry at 
HKLM\SOFTWARE\Cygwin\setup\rootdir to see if the installer recorded the dir there. If that fails it also looks for cygwin in the default Babun install location ($user_home/.babun/cygwin or something).

I'm cooking up some code now so that people can explicitly say as a command option where cygwin is located. It shouldn't take long.

**Comment by Freaky** [comment]
2016-03-17 20:43:56.415 DEBUG [main #0] Found cygwin installation: C:\cygwin64


Is this lying?

**Comment by sedwards2009** [comment]
@Freaky Is there or was there ever, a cygwin installation in C:\cygwin64? It sounds reasonable. That is the default installation directory if you use the installer.

**Comment by Freaky** [comment]
There is.

To be clear, here's the full backtrace:

    TypeError: Cannot read property 'cygwinDir' of null
    at Object.factory (C:\extraterm-0.5.0-win32-x64\resources\app\src\ptyproxy.js:106:52)
    at main (C:\extraterm-0.5.0-win32-x64\resources\app\src\main.js:49:40)
    at Object.<anonymous> (C:\extraterm-0.5.0-win32-x64\resources\app\src\main.js:584:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\extraterm-0.5.0-win32-x64\resources\app\main.js:8:1)

This hack in ptyproxy.js lets the app launch, albeit I don't actually get a shell, just a "Welcome to Extraterm!":

    var sessionProfile = config.expandedProfiles[0];
    var pythonExe = findCygwinPython("c:\\cygwin64");

**Comment by sedwards2009** [comment]
OK, it just looks like it can't find cygwin.

**Comment by Freaky** [comment]
So why does it say "Found cygwin installation"?

Lack of shell is tracked down to the dummy passwd file I made because for some reason cygwin setup didn't make one.

**Comment by Freaky** [comment]
Yup, that's it - duff passwd file causes sessionProfile to be null.  Fixing that lets me roll back my hack.

**Comment by Freaky** [comment]
And this would explain why it's missing and how to generate them if needed: https://stackoverflow.com/questions/28573763/i-am-unable-to-find-the-etc-passwd-file-in-cygwin

**Comment by sedwards2009** [comment]
I wonder if it is worth the effort to check for a nonsense value from /etc/passwd and then default to /bin/bash.

**Comment by Freaky** [comment]
To be clear, the initial error was there being *no* /etc/passwd, because cygwin doesn't create one any more.

You should really be using getpwent() rather than poking at it directly.

**Comment by nathan-sain** [comment]
extraterm also finds my cygwin directory.
```
2016-03-17 16:46:41.589 DEBUG [main #0] Found cygwin installation: C:\cygwin64
```
My issue may be related to you parsing the passwd file. I changed my home directory path in the passwd file to point outside of the C:\cygwin64 directory.
```
UCA:unused:1000:513:U-9J88PS1\UCA,S-1-5-21-1060225852-1179717075-1491434510-1000:/cygdrive/k/home:/bin/bash
```

**Comment by sedwards2009** [comment]
Cygwin doesn't create a /etc/passwd anymore?? I guess that is possible.

I would use `getpwent()` if I had it but Electron (and Extraterm) are not cygwin applications on Windows so they don't have direct access to cygwin's compatibility layer. It doesn't even have direct access to a PTY. This is why is uses Python in cygwin to act as a proxy. This python is inside the cygwin world and bridges the two.

**Comment by sedwards2009** [comment]
I've spun this missing /etc/passwd problem into its own issue #9 .

**Comment by sedwards2009** [comment]
I think I've covered the problems discussed in this thread in other issues. v0.6.0 will have these cygwin related fixes.

closing.
