### ISSUE TITLE
In cursor mode cursor seems to get stuck at images

### ISSUE THREAD

**Issue by marksandler2** [sedwards2009/extraterm#72]
Thank you for making this awesome product! On linux at least the cursor seems to get stuck whenever it encounters an image. The only way i found to unstuck is to use mouse to click elsewhere.

**Comment by sedwards2009** [comment]
You're right. I can confirm the problem. It was (should be!) possible to navigate past images using the keyboard only. It appears to be broken.

**Comment by sedwards2009** [comment]
This will be in 0.30.0.
