### ISSUE TITLE
Customize PROMPT_COMMAND

### ISSUE THREAD

**Issue by marksandler2** [sedwards2009/extraterm#73]
extraterm seems to overwrite PROMPT_COMMAND unconditionally - is there a way to change that (short of recompiling source). I can of course change it after i injected bash_integration  but this seems silly.

**Comment by sedwards2009** [comment]
I can change it to append the extra extraterm code to what ever is already in `$PROMPT_COMMAND`, and it should still work.

What kind of stuff do you have in your `PROMPT_COMMAND` anyway?
