### ISSUE TITLE
For some reason the shell doesn't show up if i don't select a "shell injection"

### ISSUE THREAD

**Issue by SolarAquarion** [sedwards2009/extraterm#81]

**Comment by sedwards2009** [comment]
Works here.

You can going to have to provide a little bit more detail about what you are using, doing and seeing otherwise I can't do anything.

**Comment by SolarAquarion** [comment]
If I launch extraterm I don't see a shell prompt, only if, and only if I
select a shell injection does the shell prompt  come into existence

**Comment by sedwards2009** [comment]
Which OS and shell are you using? This all worked in previous versions I assume. If you open up the "Developer Tools" and look in the Console tab, do you see anything interesting?
