### ISSUE TITLE
Can't change font

### ISSUE THREAD

**Issue by BackSeat** [sedwards2009/extraterm#84]
Just downloaded extraterm and tried to change font. Every time I select another font, the combo changes back to DejaVu Sans Mono a fraction of a second later.

Version: extraterm-0.33.0-linux-x64 (interestingly, the "About" menu doesn't give the version number).

If you need any more info, let me know.

**Comment by sedwards2009** [comment]
I can confirm.

**Comment by sedwards2009** [comment]
Thanks for the report. I just released version 0.33.1 specifically to fix this problem.
