### ISSUE TITLE
support Windows Subsystem for Linux

### ISSUE THREAD

**Issue by barucho** [sedwards2009/extraterm#86]
Hi 
Can you support Windows Subsystem for Linux instead of cygwin 
Windows Subsystem for Linux have better support for linux/unix tools then cygwin like python git etc ...

**Comment by sedwards2009** [comment]
Yes. I want to phase out my use of cygwin in favour of WSL where ever possible. Supporting WSL is high prio for me. Right now I'm working on adding configurable "session types" to Extraterm, then I'll release that and the next target will be WSL and probably cmd.exe and powershell too.

**Comment by sedwards2009** [comment]
This issue is resolved in the 0.35 release.
