### ISSUE TITLE
AltGr not working on Windows

### ISSUE THREAD

**Issue by riedel** [sedwards2009/extraterm#87]
Makes it impossible to typ ~ or \ on a German keyboard. Probably due to hotkey handling (Alt+Ctl)

**Comment by sedwards2009** [comment]
I can easily reproduce the problem here, and your intuition about it conflicting with the shortcut handling is right too.

**Comment by sedwards2009** [comment]
I've been looking into this tonight and have been reminded how the keyboard handling is complex and touches APIs in Electron/Chromium which are buggy and behave differently on across platforms.

I'm going to get back to this bug after the next Extraterm release, and after I've done an upgrade of the Electron version to something more recent.

**Comment by riedel** [comment]
In case it helps: https://github.com/onivim/oni/pull/717 fixes this for another Electron based project.

**Comment by sedwards2009** [comment]
I just noticed that the AltGr handling on windows is being changed in the current Chromium beta: https://www.chromestatus.com/features/5059438092222464

**Comment by sedwards2009** [comment]
This issue is resolved in the 0.35 release.

**Comment by subhead** [comment]
I have still anot working alt gr key with the latest version of extraterm 0.35.1. Before wsl is loaded completly the alt gr key is working but after wsl is loaded alt gr refuses to work.
