### ISSUE TITLE
Trouble with frames

### ISSUE THREAD

**Issue by oliversturm** [sedwards2009/extraterm#89]
I considered adding several reports, but I thought it would be better to describe these issues together and split up later.

I'm using zsh 5.2 with several oh-my-zsh plugins, plus powerline, on Linux. I have configured extraterm with Fira Code Retina.

First problem: I get frames created all the time. After first starting extraterm, I set all the Frame checkboxes on the Frames page, but I didn't create any new rules. However, for instance running `ll` renders a frame. I have not found a command that does *not* create a frame.

This leads to problem two: it seems that each frame resets the terminal. The behavior varies a bit - sometimes the terminal is reset and the new frame is shown at the top of the output, followed by the prompt. I can see this behavior with `ll`, for instance. Sometimes, I can briefly see a frame popping up before the terminal resets, and then I'm left with just the new prompt at the top. This happens with a simple `cd`, for instance.

Finally, the rendering of frames is incorrect in that the title bar of the frame partially covers the first line of text inside it:

![image](https://user-images.githubusercontent.com/4730969/39512256-2b81b910-4de8-11e8-8652-16f09743e51c.png)

Please let me know if I can help with further details or debugging.

**Comment by sedwards2009** [comment]
The idea with frames is that the output of each command is framed by default. In the frame settings you can customise the behaviour somewhat on a per command basis. i.e. you set rules which match commands and then you can disable the frame etc.

Did expect or want the default frame behaviour to be different?

Regarding the terminal being reset after every command, do you just mean that the screen is cleared and the last output is scrolled up and outside the visible window area?

Yes, I've also noticed how the contents of frames is often misaligned. It bugs me too and intend to give the problem some attention soon.

**Comment by oliversturm** [comment]
Thanks for explaining!

> Did expect or want the default frame behaviour to be different?

Yes, indeed. I thought the settings page showed how commands could have frames activated - wondered briefly about the strange set of items and the fact that they were all unchecked, but it didn't cross my mind that all commands would be framed by default.

I'm not sure whether that's a good thing... I think my initial impression is that I'd rather be using the frames for specific output only, instead of trying to disable them selectively for all commands that don't need them. Perhaps it would be a good idea to have a "use frames by default" checkbox? Then each user could easily switch between an opt-in and an opt-out usage style.

> Regarding the terminal being reset after every command, do you just mean that the screen is cleared and the last output is scrolled up and outside the visible window area?

Huh. Yes, turns out that's what I mean. I apologize, I guess I've been using tmux too much and I didn't notice that the content was available in the scrolled region.
Nevertheless, the behavior remains curious. Is it on purpose?

**Comment by withnale** [comment]
Yes. I'm struggling with the same issue, which really makes things unusable right now. Any space below your prompt is dead space and typically you want to see as much of your scrollback as possible. I know it's still present if you scroll up, but it gets annoying quickly if you are running a number of short commands which outputs 2-3 lines and you cannot see anything of the previous scrollback.

![screenshot from 2018-05-03 11-06-13](https://user-images.githubusercontent.com/1526703/39571038-21829346-4ec2-11e8-92b0-f84090150a8d.png)

In the above example, there are numerous commands and output in the history/scrollback.

**Comment by sedwards2009** [comment]
@oliversturm The whole frame settings were thrown together a long time ago and need to redone. At some stage the number of configurable options for each rule will be expanded and it won't just be one lonely checkbox. Adding something at the top for selecting the default behaviour isn't a bad idea. Even if it is not changed it will still communicate the default behaviour and make it more intelligible.

**Comment by sedwards2009** [comment]
The clearing and scrolling problem is fall-out from when I added proper support for the `clear` command. I've already tried to tweak it once, but I also can see that it gives bad results. The reason why it is hard to get right is because of how the frames and normal terminal screen/area interact.

I've got some ideas about how to improve the situation though.

**Comment by eSaner** [comment]
Would love to see a fix for the scrolling issue.

**Comment by sedwards2009** [comment]
This issue is resolved in the 0.35 release.
