### ISSUE TITLE
Can you run other shell than /bin/bash?

### ISSUE THREAD

**Issue by psprint** [sedwards2009/extraterm#91]
I would like to run /usr/local/bin/zsh-5.5.1-dev-0. Can I set this somewhere in extraterm?

**Comment by sedwards2009** [comment]
I just released this feature 2 days ago in v0.34.0. Look for "Session types" in the Settings tab.

**Comment by psprint** [comment]
Cool. I must have some older version ("About Extraterm" doesn't show version), I'm installing on OS X using Homebrew Cask, it probably downloads a dmg.
