### ISSUE TITLE
Quake mode support

### ISSUE THREAD

**Issue by sedwards2009** [sedwards2009/extraterm#93]

**Comment by sedwards2009** [comment]
@cprog To me it sounds like this can be done by implementing to features:
* Global shortcuts so that you can use Control+Tilde to bring Extraterm to the front/back.
* Option to hide Extraterm from the taskbar ans only show an icon in the tray area.

**Comment by undermark5** [comment]
I second the addition of a quake mode. I absolutely love being able to just hit a button and have a terminal drop down. I'd prefer it to have a drop down animation, but, basically if it can hide itself and reappear with the touch of a button that would make this way better in my opinion.

**Comment by cprog** [comment]
It works great for me. Thanks :) Merry Cristmas

**Comment by sedwards2009** [comment]
@cprog tha's great to hear. Merry Christmas! :christmas_tree: :santa: :gift:
