### ISSUE TITLE
0.35 release fails to load on windows

### ISSUE THREAD

**Issue by ChrisJefferson** [sedwards2009/extraterm#96]
I downloaded and opened the 0.35 release. I get the following message on open:

[screenshot](https://i.imgur.com/jQE6rrT.png)

**Comment by sedwards2009** [comment]
@ChrisJefferson Can you tell me about how you starting Extraterm and which kind of monitor/resolution you are using?

**Comment by sedwards2009** [comment]
I've now been able to reproduce the problem here by setting the scaling factor to 150%.

**Comment by sedwards2009** [comment]
It does work with scaling factor 200% and 100% though.

**Comment by sedwards2009** [comment]
Fixed in version 0.35.1.
