### ISSUE TITLE
Alt GR not working under WSL with version 0.35.1

### ISSUE THREAD

**Issue by subhead** [sedwards2009/extraterm#97]
I noticed that my Alt Gr Key is refusing to work when WSL is loaded. When i open up a normal cmd terminal Alt gr is working as expected. But as soon as i start my WSL bash the Alt Gr key stops working for me.

Windows 10 1803
extraterm 0.35.1

**Comment by subhead** [comment]
I don´t have any additional keyboard layout installed or in use exept for my main layout (german).

**Comment by subhead** [comment]
Is there anything i can provide for locating the root cause of this issue?

**Comment by sedwards2009** [comment]
Your problem doesn't appear to be Extraterm specific. It is something with your Windows install and/or programs. From what I can google up, it looks like some other apps can break AltGr when they are run. Names mentioned:

* Remote Desktop Connection
* Windows XP Mode (Virtual PC)
* EasyTune
* VMWare vCenter
* mRemote
* VirtualBox
* Ditto
* Visual Studio 2010 (an add-in perhaps?)
* Synaptics

You need to have a good look at what apps and utilities are installed and running and try to figure out if one of them is the cause. Applications which add global hotkeys could also be a problem.

**Comment by sedwards2009** [comment]
@subhead Can you check whether this is still an issue in 0.39?

**Comment by sedwards2009** [comment]
I assume the thumbs up means that this problem is now solved.
