### ISSUE TITLE
Remembering WindowsConfiguration seems not to work

### ISSUE THREAD

**Issue by jamtur01** [sedwards2009/extraterm#99]
I want Extraterm to remember my layout when I quit. I found 139dd03d475190c91e59e66cfecbe1bbcd46eecc and so assumed the `extraterm.json` file would save the state when I closed it. But it restarts without the layout and that file seems unchanged with:

```json
  "windowConfiguration": {
    "0": {
      "x": 72,
      "y": 30,
      "width": 1600,
      "height": 1020
    }
  },
```

Any trick I am missing? 

Extraterm 0.35.1 on Ubuntu 18.04 under KDE Plasma 5.

**Comment by sedwards2009** [comment]
Extraterm remembers the size and position of its window on the screen. It doesn't remember the layout of the panes and tabs.

**Comment by jamtur01** [comment]
Thanks.
